### ISSUE TITLE
[Auth][Register] Adicionar navegação para tela de Termos e Políticas de Privacidade

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#111]
## Descrição

Adicionar navegacão para a tela de termos e políticas de privacidade.

[Figma](https://www.figma.com/file/d8fHoLCnNU3EDQg0UQQTPE/Is-It-Safe%3F?node-id=862%3A1942)

## BDD

**1. A partir do cadastro** 

- Dado que qualquer usuário em processo de cadastro
- Quando o mesmo clicar no botão de "Termos de Uso e Políticas de Privacidade"
- O usuário deve ser direcionado para a tela em questão

![Image](https://user-images.githubusercontent.com/51540772/220742929-bd3de50f-bb21-478b-9531-24198dd0ef31.png)

**2. A partir do drawer** 

- Dado que qualquer usuário logado
- Quando o mesmo clicar no botão de "Termos de Uso e Políticas de Privacidade" do Drawer
- O usuário deve ser direcionado para a tela em questão

![Image](https://user-images.githubusercontent.com/51540772/220743530-798d335b-1010-488a-809e-fd14a703c0f1.png)

**Comment by Endleyson** [comment]
vou iniciar a atividade no domingo 19/03
