### ISSUE TITLE
[Account] Implementação dos testes unitários da camada de domínio do MyAccount

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#113]
## Descrição

Realizar a implementação dos testes unitários referente à camada de domínio.

**Comment by devlucasandrade** [comment]
Conforme alinhado, task foi redirecionada para @EduardaGarangau que já estava atuando.

**Comment by EduardaGarangau** [comment]
@estermabel 
Testes unitários no módulo Account estão concluídos. Serão enviados junto com os testes unitários do módulo Profile.
