### ISSUE TITLE
[Config] Implementação dos testes unitários da camada de domínio do Config

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#114]

**Comment by estermabel** [comment]
Tarefa movida para backlog pois ainda não há todas as implementações necessárias do moódulo de congifuração para poder ser realziado os testes devidos.

**Comment by feliperfdev** [comment]
@estermabel Estava vasculhando aqui e, pelo que vi, aparentemente a @EduardaGarangau já implementou os testes referentes aos usecases utilizados no módulo e submódulos de `Config`. Verificar #143
