### ISSUE TITLE
[Account] Alterar Senha

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#117]
## Descrição

Implementar tela de Alterar senha.

[Figma](https://www.figma.com/file/d8fHoLCnNU3EDQg0UQQTPE/Is-It-Safe%3F?node-id=862%3A6211)

## BDD

**1. Dado que um usuário deseja alterar sua senha**

- Dado qualquer usuário logado
- Quando o mesmo iniciar e concluir a ação de alterar senha
- Deve-se ser realizado:

      - Sucesso:
          - **Texto**: “Senha alterada com sucesso!”
          - **Tipo**: SnackBarType.success
      - Error:
          - **Texto**: “Não foi possível alterar sua senha!”
          - **Tipo**: SnackBarType.error

**Comment by feliperfdev** [comment]
Implementações até o momento:

- [x] Tela de confirmar senha está integrada ao caso de uso referente à confirmação de senha. Com isso, ao ser validada, é habilitado o botão para prosseguir para a página de alterar a senha.
- [x] Tela de alterar a senha implementada e contendo lógica referente à validação de senha (`Regular Expression`) e comparação entre nova senha e sua confirmação.
- [ ] Integração com endpoint referente a alteração de senha (pendente, pois, ainda não existe).
