### ISSUE TITLE
[Profile] Implementação dos testes unitários da camada de domínio do Profile

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#118]
## Descrição

Realizar a implementação dos testes unitários referente à camada de domínio.

**Comment by EduardaGarangau** [comment]
@estermabel 
Testes unitários no módulo Profile estão concluídos. 
Por conta do Service usado no módulo Profile ter sido alterado para realizar os testes foi preciso realizar os testes unitários também do módulo Config, principalmente do módulo Account, seus UseCases foram modificados assim como seu Bloc.
