### ISSUE TITLE
[Home] Avatar exibido no drawer não atualiza após edição

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#130]
## Descrição

O avatar exibido no Drawer não atualiza após edição.

## Passos para reproduzir (se for viável)

- Abrir o Drawer
- Clicar em “Minha Conta” 
- Clicar no Avatar para editar 
- Selecionar Avatar diferente do atual 
- Clicar em “Confirmar” 
- Receber mensagem “Avatar alterado com sucesso!” 
- Retornar a página inicial 
- Abri Drawer 
- Verificar que Avatar não foi atualizado após edição. 

## Resultado esperado

Após a edição é esperado que o avatar do drawer seja atualizado.

## Resultado atual

O avatar exibido no Drawer não atualiza após edição.

## Ambiente

Dispositivo Android

## Informações adicionais

- Avatar do perfil atualiza após a edição, mas o avatar exibido no Drawer não atualiza.
- O avatar do drawer só atualiza se o usuário sair da conta e entrar novamente

**Comment by NETfellow** [comment]
PR Aberto.
