### ISSUE TITLE
[Location] “Scrollbar de experiência” exibido nas Avaliações não condiz com as opções existentes na edição/adição de avaliação

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#132]
## Descrição

“Scrollbar de experiência” exibido nas Avaliações não condiz com as opções existentes na edição/adição de avaliação. 

## Resultado esperado

![Image](https://user-images.githubusercontent.com/51540772/221447471-00add0d2-29b0-4971-be43-cc0c99e391c8.png)

## Resultado atual

![Image](https://user-images.githubusercontent.com/51540772/221447491-c8ea9e92-e670-4b77-a2a3-8d51b39bede6.png)

## Screenshots or Logs

[Vídeo do app](https://drive.google.com/file/d/1z2nb8rBcV6b0JUhxYE02HXOSjedCw1he/view?usp=share_link)

## Ambiente

Dispositivo Android

**Comment by hastnumber1** [comment]
Imagens de como ficou o scroll depois das alterações

![Image](https://user-images.githubusercontent.com/58519231/222976162-2d768ca1-53c7-411a-9ede-3bf3c5adffaa.png)
![Image](https://user-images.githubusercontent.com/58519231/222976161-69616a01-c69d-4059-a11d-6e4f8879c061.png)
![Image](https://user-images.githubusercontent.com/58519231/222976165-56fe2b61-c6aa-4d8c-a18a-7ecd475b539a.png)
![Image](https://user-images.githubusercontent.com/58519231/222976163-a53ebce5-6ae1-4a74-90cc-6bbce2d60939.png)
![Image](https://user-images.githubusercontent.com/58519231/222976164-6da89497-0347-4f33-996f-faefedc270dd.png)
