### ISSUE TITLE
[Location] Layout de texto quebra quando zoom da tela é ativado

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#133]
## Descrição

O avatar exibido no Drawer não atualiza após edição.

## Resultado esperado

Texto se adaptar ao layout no modo zoom-in.

## Resultado atual

O texto fica cortado em alguns componentes.

## Screenshots or Logs

![Image](https://user-images.githubusercontent.com/51540772/221448471-e693815a-a02f-4bb1-ac5a-385adca265ea.png)

## Ambiente

Dispositivo Android Xiaomi

**Comment by devlucasandrade** [comment]
Confirmar mudança nos textos para linha de experiência da inssue #132 ou manter o figma.

**Comment by devlucasandrade** [comment]
**Ajuste realizados com base no Moto G60**

Fonte em tamanho padrão
![Image](https://user-images.githubusercontent.com/98838229/222733079-ad8be7ad-c65a-4199-8bbd-cc5a60c72e87.png)

Fonte em tamanho grande
![Image](https://user-images.githubusercontent.com/98838229/222733322-9a172f75-0136-4df9-b5dc-c504486b8821.png)

Fonte em tamanho enorme
![Image](https://user-images.githubusercontent.com/98838229/222733644-0d5eb968-a53b-46a8-b307-349e51804609.png)


Validar antes de realizar o PR

**Comment by devlucasandrade** [comment]
Alinhado ajustes nos widgets para não quebrar os textos e gráficos
Realizado no Moto G60

Fonte normal do celular
![image](https://user-images.githubusercontent.com/98838229/222808584-2fef81b8-dce1-44ab-a6c1-5694de512d30.png)

Fonte grande de celular
![image](https://user-images.githubusercontent.com/98838229/222808840-29d11e44-0c77-43c5-9d8e-c54452e04af7.png)

Fonte enorme do celular
![image](https://user-images.githubusercontent.com/98838229/222808974-f3659b15-ec6c-4f6c-8590-92ccce5982ce.png)

**Comment by devlucasandrade** [comment]
Ajuste na exibição das reviews
- Texto inicial saindo do padrão (_O que estão falando sobre esse local:_)
- Data cortando

Fonte padrão
![image](https://user-images.githubusercontent.com/98838229/222814340-3d86cdd2-2e9d-4d38-b4ee-a2774edc83c6.png)

Fonte grande
![image](https://user-images.githubusercontent.com/98838229/222817928-66526ca1-143b-45e4-bc93-aecb0cb8fb3d.png)

Fonte enorme
![image](https://user-images.githubusercontent.com/98838229/222820371-a7d3efa8-b4b8-43ec-955a-a22c51762087.png)

**Comment by devlucasandrade** [comment]
Ajuste realizado para quando a nota for zero, não ser exibida.
![image](https://user-images.githubusercontent.com/98838229/222990697-875d2324-274a-45ab-a68a-dcef9f3b99d4.png)
![image](https://user-images.githubusercontent.com/98838229/222990713-d31cbe7e-1f97-48e9-b0b4-0e20a64f8bca.png)
