### ISSUE TITLE
[Home] Exibir lugares próximos

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#135]
# BDD

## User Story

Como um usuário, eu quero poder visualizar locais próximos à mim, para que seja mais fácil de encontrar locais para frequentar.

## Acceptance Criteria

    Given A localização atual do usuário  
    When  Quando ele acessar a aba de "Lugares Próximos" 
    Then  Deve ser retornado uma lista de locais próximos a ele

### Description

Recuperar a localização do usuário e armazena-la localmente sempre que o mesmo usuário acesse a página "Home".

### Acceptance Criteria

    Given Um usuário logado 
    When  Ele acessar a "Home" 
    Then  O mesmo deve ter sua localização atual identificada e armazenada

**Caso seja o primeiro acesso do usuário, deve ser solicitado ao mesmo que seja permitido o uso de sua localização. Caso ele não libere, sempre que ele acessar qualquer uma das abas da "Home" deve ser apresentado o Empty State referente e um botão o direcionando para as configurações de localização nativas do dispositivo do usuário.**

### Description

Ao acessar a aba de "Lugares Próximos" deve ser feito uma requisição à API, para que seja retornado os locais próximos àquele usuário.

### Acceptance Criteria

    Given Um usuário logado 
    When  Ele acessar a aba "Lugares Próximos" 
    Then  Deve ser requisitado ao serviço a lista referente aos locais próximos do mesmo

### Description

Ao finalizar a requisição, deve ser exibido a lista de locais para que usuário possa visualizar.

### Acceptance Criteria

    Given Um usuário logado 
    When  A requisição de locais próximos for finalizada 
    Then  Deve ser exibido ao usuário a lista de locais próximos retornadas pela API

### Description

Caso não seja possível retornar os itens da API.

### Acceptance Criteria

|Context| Action 
|--|--|
|Retorno vazio da API|Exibir para o usuário o empty state referente sem o botão de redirecionamento para as configurações
|Localização não autorizada|Exibir para o usuário o empty state referente com o botão de redirecionamento para as configurações
|Erro ao armazenar a localização do usuário|Exibir snackbar com o texto "Não foi possivél salvar sua localização, tente novamente em instantes!"
|Erro ao recuperar a localização do usuário|Exibir snackbar com o texto "Não foi possivél recuperar sua localização, tente novamente em instantes!"
|Erro ao realizar a requisição para API|Exibir snackbar com o texto "Não foi possivél recuperar locais próximos à você, tente novamente em instantes!"

## Additional Information

O processo de captura de localização já foi implementado, contudo, é preciso que seja feito uma nova verificação do sucesso de captura e recuperação da localização do usuário.

**Comment by devlucasandrade** [comment]
## Cenário 3
- Verificar se dentro dos valores de busca está bom ou precisa de uma busca com um valor maior
![image](https://user-images.githubusercontent.com/98838229/226491381-09a7b9a1-1a63-4d09-97a7-cca975996b41.png)

**Comment by devlucasandrade** [comment]
Código apresentando as mensagens, mas com erros no momento de utilizar o TAB pela app bar e ao puxar a tela para ser exibida, criando diversas caixas de diálogo para indicar que o serviço está desativado. Verificar com @feliperfdev assim que possível
