### ISSUE TITLE
[Auth][Register] É possível avançar no cadastro com dados inválidos

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#137]
## Descrição

Durante a realização de testes foi identificado alguns cenários que serão exemplificados abaixo.

### Cenário 1

Case de Sucesso: Nome de usuário deve ter mais de 3 letras e menos de 10

- É possível avançar no cadastro com usuário contendo somente 2 letras.
- É possível avançar no cadastro com usuário contendo mais de 10 letras.

### Cenário 2

Case de Sucesso: Senha deve ter 8 ou mais caracteres

- É possível avançar no Cadastro com número de caracteres menor que 8

### Cenário 3

Case de Sucesso: ’Confirmar senha’ deve ter o mesmo conteúdo de Senha

- Avança o cadastro sem as senhas serem correspondentes

### Cenário 4

Case de Sucesso: A etapa de perfil deve ser opcional para conclusão do cadastro e o conteúdo do dropdown deve ser carregado ao acessar a tela

- Na tela de título “Perfil”: os dois campos abaixo do campo “data de nascimento” não carregam para possível preenchimento. Mostra a mensagem "Carregando...", impossibilitando a finalização do Cadastro.
- Os botões “Avançar” e “Finalizar” não respondem ao clique.

**Comment by devlucasandrade** [comment]
Refiz a branch, porque a anterior estava antiga.

**Comment by devlucasandrade** [comment]
- Ajustes básicos realizados, mas será necessário realizar uma revisão e testar os campos e validações.
- Verificar desativação do botão finalizar, caso não sejam preenchidos os dados de avatar, nasc, gênero e orientação.

**Comment by devlucasandrade** [comment]
- [ ] Cenário 1 - Usuário tem que ter mais que 3 caracteres e o campo está limitado a 10;
- [ ] Cenário 2 - Senha tem que ter 8 ou mais caracteres, tendo que ter no mínimo 1 letra e 1 numero
- [ ] Cenário 3
- [ ] Cenário 4

- [ ] Usuário ao clicar em avançar, ele realiza o cadastro sem necessidade de preencher os dados da segunda tela (avatar, nasc., gênero e orientação)
- [ ] Usuário ao clicar em finalizar, precisa preencher os campos (avatar, nasc., gênero e orientação)

**Comment by devlucasandrade** [comment]
- Ao apresentar erro em tela, os campos já preenchidos precisam ser preenchidos novamente, os controllers não salvam em memória ram o que foi digitado.
- Verificar retorno de validação do StreamSafeDropbox pois ao clicar no finalizar, caso não seja informado nenhum valor, ele apresenta erro pois o título está como vazio. ""
