### ISSUE TITLE
[Location] Ajustar exibição do gráfico de um local

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#140]
# BDD

## User Story

Como um usuário, eu quero poder visualizar detalhes do gráfico de um local, para que seja mais fácil de interpretar as avaliações.

## Acceptance Criteria

No endpoint de GetLocationById, deverá ser mapeado o novo campo "chart" para que seja possível passar os devidos valores para o componente abaixo.

![Image](https://user-images.githubusercontent.com/51540772/222988195-288b8d61-ce9b-42ef-a59d-976957aca2bd.png)

## Atividade

1. Ajustar model de Location para ser possível capturar os dados do gráfico da API
2. Ajustar a exibição do gráfico, passando para o componente os valores corretos para sua exibição

## Observação

Atividade mediante conclusão de: [[Location] Adicionar informações no endpoint de getLocationById](https://github.com/Is-It-Safe/api/issues/37)

**Comment by devlucasandrade** [comment]
Feature realizada por @estermabel no final de semana.
