### ISSUE TITLE
[Home] Ao acessar aba de "Melhores Avaliados" a lista de locais é duplicada

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#142]
## Descrição

 Ao acessar aba de "Melhores Avaliados" a lista de locais é duplicada

## Resultado esperado

Que a lista não seja duplicada ao trocar as abas.

## Resultado atual

https://user-images.githubusercontent.com/51540772/223277193-a5fab308-1b10-4fae-95c4-7b9d7d611d37.mp4

## Ambiente

Emulador Android

**Comment by Endleyson** [comment]
Pull Request #144
