### ISSUE TITLE
[Profile] Erro ao exibir "Minhas Avaliações"

### ISSUE THREAD

**Issue by estermabel** [Is-It-Safe/mobile#155]
## Descrição

Quadro cinza sobrepondo a tela de “Suas Avaliações”

## Resultado esperado

Exibir lista de avaliações realizadas pelo usuário.

## Resultado atual

**![](https://lh4.googleusercontent.com/Nj6GfZDqKFYsgsgPpFW-65BdwIQJ61BwscsWDXrx006rXIdHF1gZrpKUyVxxm9zfmiqlR3v6fAaz9O8Le9xszuHpKlAZ7zUGa_hnpbtQo_6USf9LsZQAQbzFN_P4iMTxT5W6cjXuBsU6S9bCG3hWKqQ)**

**Comment by devlucasandrade** [comment]
Correção foi realizada nas atualizações e correções feitas por Ester nos merges anteriores.
Atualmente está funcionando corretamente.
