### ISSUE TITLE
[BUG] - Dispose sendo chamado ao cancelar ação de cadastro

### ISSUE THREAD

**Issue by yllo-luis** [Is-It-Safe/mobile#190]
## Description

Ao avançar em etapas de cadastro o metodo dispose da classe `RegisterProfileBloc` esta sendo chamado causando problemas em etapas de cadastro já feitas pelo usuário.

## Steps to Reproduce (if applicable)

1. Iniciar modulo de cadastro;
2. Realizar primeira étapa de cadastro de dados de forma valida;
3. Ao avançar para tela para escolha de avatar cancelar cadastro;

## Expected behavior

Ao retornar para a tela de seleção de avatar dados como gênero e orientações sexuais já deveriam estar carregados e prontos para uso.

## Actual behavior

Ao retornar para a teka de seleção de avatar dados que deveriam estar já disponíveis ao usuário ficam em carregamento eterno.

## Screenshots or Logs

![Screenshot_20230329_181505](https://user-images.githubusercontent.com/28909884/228669921-83e072f7-fd95-4614-9943-644fe6a7501f.png)

## Environment

Operating System: Android
Browser (if applicable):
Version: 1.0.2v

## Additional Information

Percebi um warning durante a reprodução do bug.

```
I/flutter (25919): [2023-03-29 17:58:03.598894 | Catcher | INFO] setState() or markNeedsBuild() called when widget tree was locked.
I/flutter (25919): This SafeBuilder3<RegisterEntity?, bool, bool> widget cannot be marked as needing to build because the framework is locked.
I/flutter (25919): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (25919):   SafeBuilder3<RegisterEntity?, bool, bool>
```

**Comment by NETfellow** [comment]
Estou atuando em conjunto com a tarefa [154](https://github.com/Is-It-Safe/mobile/issues/154).

Acredito que devo ter a resolução de ambos em breve.
