### ISSUE TITLE
[QA] - Texto de descrição da localização dos estabelecimentos sem espaço após as vírgulas

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#198]
## Description

Texto de descrição da localização dos estabelecimentos sem espaço após vírgulas.

## Steps to Reproduce (if applicable)

Abra o app > Entre com uma conta válida > Busque qualquer estabelecimento > Verifique texto de localização.

## Expected behavior

Espaço após a vírgula, de acordo com a gramática normativa

## Actual behavior

Textos de localização sem espaço após a vírgula

## Screenshots or Logs

![Screenshot_20230405-154051](https://user-images.githubusercontent.com/126485540/230178305-cbd7acfb-ebd0-40d2-b0ff-51be073c5cf9.png)

## Environment

Operating System: Android 10 Xiaomi mi a2
Browser (if applicable):
Version: 1.0.2

## Additional Information

[Add any other relevant information about the issue or feature request here.]

**Comment by bruno-luzardi** [comment]
@hastnumber1 conseguiu finalizar o code review desta demanda ?

**Comment by hastnumber1** [comment]
Added raplaceAll() to give spacing after commas

**Comment by devlucasandrade** [comment]
Apk para realização dos testes - https://drive.google.com/file/d/1cO28LsjPZbpaPljaveqrUxjj5zI49dkC/view?usp=drive_link
Caso não consiga acessar, por favor me pede para enviar pelo Discord

**Comment by bruno-luzardi** [comment]
Boa tarde @devlucasandrade  @flaviomelodev , realizei alguns testes com a apk disponibilizada, as abas da tela de inicio precisam ser tratadas incluindo o espaço após as virgulas, segue abaixo evidências do teste.

_Tela Inicio
Aba Lugares proximos: não tem espaço no texto após as virgulas.
Aba melhores avaliados: não tem espaço no texto após as virgulas._


Tela inicio - aba lugares próximos:


![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/577263d9-e51e-4e82-9769-a0e55eb5865a)



tela inicio - aba melhores avaliados



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/e0fe8d57-b750-4863-98e7-8acf334bfb5e)

**Comment by bruno-luzardi** [comment]
Importante: Verificar com o time do APP se o espaçamento sem virgulas é o suficiente na visualização do endereço ou se devemos acrescentar outros caracteres como no exemplo: `Salvador - BA`

Esta questão sobre o retorno do estado irei validar com o pessoal de design.

**Comment by bruno-luzardi** [comment]
@marckdados por favor, suba este ajuste para o ambiente de produção.
