### ISSUE TITLE
[BUG] - Delay ao acessar tela "Minha Conta"

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#200]
## Description

Delay ao acessar tela "Minha Conta"

## Steps to Reproduce (if applicable)

Abrir Drawer > Clicar em "Minha Conta" > Verificar atraso no carregamento das informações da tela

## Expected behavior

Acesso à tela sem atraso de carregamento das informações 

## Actual behavior

Delay (1-2s) no carregamento de informações

## Screenshots or Logs

![Screenshot_20230405-165356](https://user-images.githubusercontent.com/126485540/230194425-88ddae0d-ac64-4296-abc1-7713badb6c60.png)

## Environment

Operating System: Android 10
Browser (if applicable):
Version: 1.0.2

**Comment by estermabel** [comment]
Isso ocorre, devido à busca das informações da API. Realmente vai ter delay a menos que tenhamos um banco local, o que não temos no momento.
