### ISSUE TITLE
[Register] - Impossivel finalizar cadastro.

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#212]
## Description

Não é possível finalizar cadastro

## Steps to Reproduce (if applicable)
Preencher todos os campos com informações válidas > Clicar em "Finalizar" > Verificar mensagem "Erro ao realizar o cadastro. Tente novamente mais tarde." 

## Expected behavior

Realizar cadastro com sucesso

## Actual behavior

--

## Screenshots or Logs

https://user-images.githubusercontent.com/126485540/232796217-4318135f-f556-48cb-864c-2eb5838cb5fa.mp4

## Environment

Operating System: Android 10
Browser (if applicable):
Version: 1.0.3

## Additional Information

--

**Comment by yllo-luis** [comment]
Estou tendo dificuldades para reproduzir o bug mencionado nesta issue.

Temos algum fluxo em especifico que possa causar a falha?

[screencast-Genymotion-2023-04-20_15.03.33.897.webm](https://user-images.githubusercontent.com/28909884/233451082-5a9e9033-e5c7-48bb-9aef-1e5e51c8447f.webm)

**Comment by estermabel** [comment]
Problema ainda persiste.
