### ISSUE TITLE
[BUG] - Nenhum lugar próximo é exibido 

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#220]
## Description

A tela "Lugares Próximos" não exibe nenhum estabelecimento

## Steps to Reproduce (if applicable)

[If the issue is a bug or error, provide steps to reproduce the issue. If it's a feature request, skip this section.]

## Expected behavior

Exibição de estabelecimentos próximos, de acordo com a localização do usuário.

## Actual behavior
Não há exibição de estabelecimentos 

## Screenshots or Logs
![Screenshot_20230426-204151 (1)](https://user-images.githubusercontent.com/126485540/234726127-c1b28d21-0fba-4bab-b978-c38bbfeae60b.png)

## Environment

Operating System:
Browser (if applicable):
Version: 1.0.4

## Additional Information

[Add any other relevant information about the issue or feature request here.]

**Comment by devlucasandrade** [comment]
Lugares próximos sendo exibidos normalmente. Quando fiz a correção do BUG na tela de Locais próximos, ele sempre exibiu normalmente.

**Comment by estermabel** [comment]
Atualmente só tem locais no banco da cidade de Salvador-BA
