### ISSUE TITLE
[BUG] - Não é possível adicionar novo local/estabelecimento

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#221]
## Description

Não é possível adicionar novo estabelecimento. A seguinte mensagem de erro é exibida: "Não foi possível salvar o local. Tente novamente mais tarde."

## Steps to Reproduce (if applicable)

Login com conta válida > Clicar em "Buscar" > Pesquisar por local não cadastrado no app > Quando não encontrar o app retornará opção de "Adicionar local" > Clicar em Adicionar Local > Preencher com informações válidas > Clicar em "Adicionar Local" > Verificar seguinte mensagem: "Não foi possível salvar o local. Tente novamente mais tarde."

## Expected behavior

[Describe what you expected to happen.]

## Actual behavior

[Describe what actually happened.]

## Screenshots or Logs

https://user-images.githubusercontent.com/126485540/234728655-ee6da908-9b8b-4f0a-837c-8ac530b854c8.mp4

## Environment

Operating System: Android 10
Browser (if applicable):
Version: 1.0.4

## Additional Information

[Add any other relevant information about the issue or feature request here.]

**Comment by devlucasandrade** [comment]
Na versão atual está salvando normalmente, mas com um erro no tipo do local.
Quando salvei ele como **Local público** ficou como **Casa noturna**.


![Image](https://user-images.githubusercontent.com/98838229/236081818-b40379e7-db6d-46b0-a3d0-723a086247df.png)
