### ISSUE TITLE
[LOGIN] - Funcionalidade "Esqueceu sua senha?" desabilitada

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#222]
## Description

Funcionalidade de Login "Esqueceu sua senha?" desabilitada

## Steps to Reproduce (if applicable)

Clicar em "Esqueceu sua senha?" > Verificar que não direciona à nova tela

## Expected behavior

[Describe what you expected to happen.]

## Actual behavior

[Describe what actually happened.]

## Screenshots or Logs

https://user-images.githubusercontent.com/126485540/234962340-cc787177-4662-4c9a-8b0a-4cb832929e68.mp4

## Environment

Operating System: Android 10
Browser (if applicable):
Version: 1.0.4

## Additional Information

[Add any other relevant information about the issue or feature request here.]

**Comment by yllo-luis** [comment]
Consegui reproduzir esta issue na branch DEV.

Irei verificar se consigo resolver de forma rápida, temos uma tarefa pronta para essa issue?
