### ISSUE TITLE
[Drawer] Implementar navegação para tela de 'Adicionar Local' no menu principal

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#268]
## User Story

**COMO** usuário do aplicativo
**QUERO** ter uma opção no menu principal para adicionar local
**PARA** que eu consiga acessar de forma fácil a opção de Adicionar locais

## Descrição
Acesso:

1. Realizar login no app
2. Acessar o Menu principal
3. Clicar na opção "Adicionar local"
4. Preencher os campos na tela e confirmar o cadastro do local.

## Critério de Aceite

- [x] Exibir a opção Adicionar Local no menu principal do app.
- [x] Permitir acesso a tela de Adicionar Local através da opção "Adicionar Local" no menu principal.
- [x] Após adicionar um local e dar um feedback ao usuário voltar ao Menu Inicio -> Aba Lugares Próximos.
- [x] Seguir o design do figma:
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=1050-3676&mode=design&t=noN6Hy4v003562rB-4

## Cenários de Teste

- [ ] **Cenário**: Adicionando local através do menu principal
**Dado** que o usuário esteja logado no app
**E** selecione a opção Adicionar local no menu principal
**E** acesse a tela Adicionar local
**Quando** for finalizado o cadastro do local
**Então** deverá ser dado um feedback ao usuário
**E** voltar ao Menu Inicio na aba Lugares Próximos

**Comment by bruno-luzardi** [comment]
Imagem da tela Adcionar Local


![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/a8fec464-69fd-463e-bf25-c03977093ba5)

**Comment by flaviomelodev** [comment]
Finalizado

https://github.com/Is-It-Safe/mobile/assets/58519231/2611add7-97c0-4583-b242-0e24ad4908d0

**Comment by Rodrigo-Motta-QA** [comment]
Olá, Flavio
Poderia disponibilizar essa versão do aplicativo em que você realizou o teste evidenciado acima?

**Comment by flaviomelodev** [comment]
Opa, Mabel geral uma nova de develop.
Vc consegue pegar nas actions

**Comment by Rodrigo-Motta-QA** [comment]
| **ID do Caso de Teste** | CT#268-001                                  |
|--------------------------|----------------------------------------|
| **Descrição**               | Validar a implementação da função "Adicionar Local" no menu principal  |
| **Pré-condições**        | 1. Usuário possui credenciais válidas     |
|                                      | 2. Usuário estar conectado no app     |
| **Passos de Execução**   | 1. Clicar no menu principal            |
|                                         | 2. Clicar em Adicionar Local           |
|                                         | 3. Inserir dados do local    |
|                                         | 4. Clicar no botão "Adicionar Local"     |
| **Dados de Entrada**      | Nome do local, CEP, Endereço e Tipo de local   |
| **Resultado Esperado**    | Local cadastrado com sucesso e feedback é dado ao usuário     |
| **Critérios de Aceitação**| 1. Exibir a opção Adicionar Local no menu principal do app. |
|                                           | 2. Permitir acesso a tela de Adicionar Local através da opção "Adicionar Local" no menu principal.
|                                           | 3. Após adicionar um local e dar um feedback ao usuário voltar ao Menu Inicio -> Aba Lugares Próximos.
|                                            | 4. Seguir o design do figma: https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=1050-3676&mode=design&t=noN6Hy4v003562rB-4
| **Pós-condições**         | Usuário é direcionado para a tela Menu inicio de Lugares próximos |
| **Resultado do teste**  | Passou|

![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/be372ccc-aef2-47d1-998b-47ad7905ed0e)



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/f5f262ee-ff30-4917-99ed-e06f3488e053)



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/5199b6a9-935c-4c03-9ce8-bc9a33cde7e2)



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/b8c322a2-5b01-423b-8216-85b620bda76d)

**Comment by Rodrigo-Motta-QA** [comment]
Teste finalizado.
@flaviomelodev 
@LetRicette 
@bruno-luzardi 
@AdrianaBispo
