### ISSUE TITLE
[Auth][Register] Permitir o uso de caracteres especiais na criação de senha durante o cadastro

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#274]
## User Story

**COMO** um novo usuário me cadastrando no app
**QUERO** poder utilizar caracteres especiais no campo senha
**PARA** que eu possa criar uma senha segura

## Descrição

Atualmente, os fluxos de reset de senha e de login permitem o uso de senhas contendo caracteres especiais, por isso, iremos ajustar o fluxo de cadastro para que, ao criar a senha no fluxo de cadastro, o usuário siga o mesmo padrão dos demais fluxos.

## Critério de Aceite

- [x] No fluxo de Cadastro, os campos senha e confirmação de senha devem ter as mesmas regras de criação de senha que já existem nos demais fluxos do app, conforme anexo abaixo:

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/9bca2631-5d28-4a7a-8ee9-5383496980f8)

- [x] Seguir o design definido no figma, conforme link abaixo:
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=5876-7009&mode=design&t=z8dVL5HyNGA42hDS-4

## Cenários de Teste

- [ ] Cenário: Realizar cadastro com senha que atenda as regras necessárias para criação de senha
**Dado** que um novo usuário esteja se cadastrando no app
**Quando** a senha informada pelo usuário atender as regras necessárias
**Então** o sistema deve permitir que o cadastro seja realizado
**E** dar um feedback ao usuário sobre o cadastro realizado

- [ ] Cenário: Realizar cadastro com senha que não atenda as regras necessárias para criação de senha
**Dado** que um novo usuário esteja se cadastrando no app
**Quando** a senha informada pelo usuário não atender as regras necessárias
**Então** o sistema não deve permitir que o cadastro seja realizado
**E** dar um feedback ao usuário para que se atente as regras de criação de senha

## Informações Adicionais

Atualmente o sistema esta barrando o uso de caracteres especiais na criação de senha no cadastro do app, porém, não existe uma mensagem clara para o usuário informando se pode ou não ser utilizado caracteres no campo de senha.

![Image](https://user-images.githubusercontent.com/136942442/247640312-6558df7c-ddf8-40a8-b53a-a0d7ac1d11bd.png)

**Comment by bruno-luzardi** [comment]
Hoje alinhei com a @jessicacfd o ajuste necessário no figma para seguirmos com a implementação desta US.

**Comment by bruno-luzardi** [comment]
OBS: Verificar com design qual a melhor forma de tratar as regras de senha descritas nesta tela ( sugestão seria seguir o modelo do gmail)
@jessicacfd  o que você acha da sugestão abaixo ?



![Image](https://user-images.githubusercontent.com/136942442/247974613-9a9ba207-da3a-4700-b850-df16d3c21261.png)

**Comment by jessicacfd** [comment]
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=3882-4743&mode=design&t=eCNaxP4W7OVidG28-4


Alteração no figma

**Comment by bruno-luzardi** [comment]
senhas para testes:
xH9458A:n%<$PH_
o8N:A4M2*sD@C4V5?~X2

**Comment by bruno-luzardi** [comment]
Validação realizada e esta ok, foram criados 2 novos cadastros com os usuários abaixo:



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/e1561062-e6f6-4f9e-bf3b-43a7d6b11ac3)



Foram realizados testes com cadastros onde a senha atendia as regras para criação de senha e testes com cadastros onde a senha não atendeu as regras necessárias.
