### ISSUE TITLE
[BUG] - Tela de login não acessa à página de Esqueceu a Senha

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#288]
## Descrição

Na tela de login do app quando o usuário clica na opção "Esqueceu a senha?" o app não esta abrindo a tela "Esqueceu a Senha" onde é informando o e-mail para enviar o link de resete de senha.

A Tela de login do app não realiza o acesso à página de Esqueceu a Senha mesmo com o certificado ssl desabilitado.

## Etapas para reproduzir (se aplicável)

Acessar tela de login do app > clicar na opção "Esqueceu a Senha?"

## Comportamento esperado

ao clica na opção "Esqueceu a Senha?" o app deve abrir a Tela de Esqueceu a Senha;

## Comportamento real

O app não esta abrindo a tela "Esqueceu a Senha" onde é informando o e-mail para enviar o link de resete de senha.

## Capturas de tela ou logs

[Se aplicável, inclua capturas de tela ou registros relevantes para ajudar a explicar o problema.]

## Ambiente

Sistema operacional: Android
Navegador (se aplicável):
Versão do app: v1.0.6+12

## Cenários de Teste

- [ ] Cenário: Acessando a opção Esqueceu a Senha na tela de login
**Dado** que esteja na tela de login do app
**Quando** clicar na opção "Esqueceu a Senha?
**Então** o app deverá abrir a tela Esqueceu a Senha.

## Informações adicionais

A opção Esqueceu a Senha já existia na tela de login do app, a Mabel removeu esta opção até que o problema de acesso seja resolvido, abaixo segue uma imagem da tela com a opção citada.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/74cc85cd-4dca-4171-b1d7-5999747506c1)

**Comment by bruno-luzardi** [comment]
@yllo-luis conforme falamos via chat, poderia por favor atuar na correção deste problema ?
Obrigado

**Comment by devlucasandrade** [comment]
@bruno-luzardi  segue link da APK para testes - https://drive.google.com/file/d/13voxcdZbgs1HE0j0KfZk6FW-jaI_S6a3/view?usp=sharing

**Comment by bruno-luzardi** [comment]
Com a APK apontando para PRD que a Mabel gerou em 18/10/23, confirmei que a opção Esqueceu a senha esta ok.



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/80ef725b-dc7c-4041-9b56-5076605310f0)
