### ISSUE TITLE
[BUG] [Add Location] Criar validação com feedback para cep inválido na tela de Adicionar Local

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#308]
## Descrição

**Como** usuário do app
**Desejo** receber um feedback caso informe um cep inválido
**Para** que eu cadastre um local com cep válido

Atualmente não existe validação do cep informado na tela de adicionar local, com isso, quando o usuário esta adicionando um local, se o cep informado for inválido, ao clicar no botão Adicionar Local o app mostra uma mensagem que não fica claro para o usuário onde esta o problema.

## Etapas para reproduzir (se aplicável)

1. Acessar o menu buscar
2. Realizar uma busca e quando a busca não retorna um local a opção "adicionar local" é habilitada
3. Acessar opção Adicionar Local
4. Será aberta a Tela de Adicionar Local.
5. Informar um cep inválido ao adicionar um local nesta tela

## Comportamento esperado

- [x] Na tela de Adicionar Local, deverá existir uma validação do cep informado pelo usuário para que um local só seja salvo com cep válido.
- [x] Para o caso da validação no campo de cep, o box do campo deve permanecer vermelho e com a msg de erro alertando sobre cep inválido, mesmo que o usuário mude o cursor para outro campo.
- [ ] A snackbar com fedback sobre cep inválido deve ser exibida antes de salvar um local.
- [x] O usuário deverá ter opção de corrigir o cep antes de salvar o local.
- [x] Enquanto o cep for inválido o local não poderá ser salvo.
- [ ] A snackbar com feedback sobre cep inválido não deverá ser exibida em outra tela.

Seguir o figma:
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=4278-7839&mode=design&t=QOWGSEE7JrdVah2y-4

## Capturas de tela ou logs

abaixo um vídeo com um cenário onde o erro acontece.

https://github.com/Is-It-Safe/mobile/assets/136942442/f48c9b32-424c-4cfa-be10-4bc08afd60e2

## Ambiente

Sistema operacional: Android
Navegador (se aplicável):
Versão do app: v1.0.7+14
Ambiente: Produção

## Cenários de Teste

- [ ]  Cenário: Adicionando local com cep inválido
**Dado** que insira uma informação no campo cep
**Quando** o app validar a informação inserida
**E** constatar que se trata de um cep inválido
**Então** deverá ser exibido um feedback para o usuário indicando que o cep é inválido
**E** o feedback deve estar no padrão definido no figma

- [ ]  Cenário: Adicionando local com cep válido
**Dado** que insira uma informação no campo cep
**Quando** o app validar a informação inserida
**E** constatar que se trata de um cep válido
**Então** deverá permitir que o local seja adicionado com sucesso

**Comment by bruno-luzardi** [comment]
- [ ] Alinhar com Jessica mensagem a ser apresentada quando o cep for inválido
- [ ] validar com Jessica se podemos colocar uma mascara no campo cep



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/588c8af5-c560-45b7-97b9-b83e789f6a28)

**Comment by flaviomelodev** [comment]
Criada máscara para CEP e feita a validação através da API viacep
O que foi feito?

Criada máscara para CEP e feita a validação através da API viacep

Tipo de Mudança:
[x] bug

**Comment by bruno-luzardi** [comment]
@flaviomelodev  @yllo-luis 

Após alguns testes encontrei os seguintes problemas:
Ao cadastrar um local, não esta sendo realizada a validação do cep, pois, após informar o cep o sistema já pula direto para o  feedback que o local foi enviado para revisão.
O sistema permitiu deixar o campo cep vazio e ao clicar em adicionar local informou que o cep é inválido.

Segue vídeo com evidências do teste realizado, favor verificar e realizar os ajustes necessários.

https://github.com/Is-It-Safe/mobile/assets/136942442/073ded4f-b7f7-4bf0-bfac-be816fc41e3a

**Comment by flaviomelodev** [comment]
Feitas as alterações solicitadas no PR.

Não coloquei 'Utilize apenas números' porque não tem como o usuário usar letras ou símbolos

**Comment by bruno-luzardi** [comment]
boa noite @flaviomelodev , realizei alguns testes e ainda existem problemas correção entregue, segue anexo evidência do testes.

O campo cep não esta validando a informação inserida.
O feedback apresentado ao usuário não deixa claro qual o problema e esta sendo exibido na tela de busca.




https://github.com/Is-It-Safe/mobile/assets/136942442/c4f50da8-a6d0-4b3f-a8f9-8db6467ebd25

**Comment by bruno-luzardi** [comment]
@flaviomelodev  agora esta ok, podemos subir em produção.

Abaixo evidências do teste.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/70faa793-cb48-4384-a4f9-02a83ee74c61)



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/96e9af18-8b10-4bbb-80dc-7b587818b7d7)
