### ISSUE TITLE
[Bug][Ambiente dev] Erro ao salvar edição de dados da conta

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#309]
## Descrição do problema

No ambiente de dev, ao acessar a tela de edição da conta e editar a informação de algum campo quando o usuário clica no botão Atualizar informações o sistema esta apresentando o erro:  **Não foi possível atualizar as informações!**

## Etapas para reproduzir (se aplicável)

Acessar menu suspenso > opção Minha conta > acessar o menu Editar perfil > editar a informação de algum campo > clicar no botão atualizar informações

## Comportamento esperado

Ao clicar no botão atualizar informações o sistema deverá salvar todas as alterações realizadas pelo usuário.

## Capturas de tela ou logs

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/ae031ff0-9f48-4cf7-8daf-1e41bb58d7cb)

## Ambiente

Sistema operacional: Android
Navegador (se aplicável):
Versão do app: v1_0_6+14 (https://drive.google.com/file/d/1jS7eRkkmKcWImBYukKTYVKLYgWS9Rpfr/view?usp=share_link)
Ambiente: Dev

## Cenários de Teste

- [ ] - [ ] Cenário: Editar dados na tela Editar Conta
**Dado** que esteja na tela de edição de conta
**Quando** for alterada a informação de algum campo
**E** clicar no botão Atualizar Informações
**Então** o sistema deverá salvar as informações que foram alteradas.

## Informações adicionais

Link da APK do ambiente de dev:
https://drive.google.com/file/d/1jS7eRkkmKcWImBYukKTYVKLYgWS9Rpfr/view?usp=share_link

**Comment by flaviomelodev** [comment]
O que foi feito?
Ajustado o retorno do textfield em caso de sucesso

Não aparecerá mais a borda vermelha no textfield

Tipo de Mudança:
[x] bug

Validações:
Testes Unitários:
 Meu código possui os devidos testes unitários
Layout:
[x ] Não houveram mudanças nas telas

https://github.com/Is-It-Safe/mobile/assets/58519231/2805a5db-a2a9-4b7d-b989-4760bb1f9562

**Comment by bruno-luzardi** [comment]
@flaviomelodev realizei testes e continua apresentando erro ao salvar os dados, favor verificar o que pode estar acontecendo.



https://github.com/Is-It-Safe/mobile/assets/136942442/9d29a997-d639-4084-8237-643b473d4ff9

**Comment by bruno-luzardi** [comment]
Por enquanto, como este bug esta apenas na versão de dev iremos pausar esta análise para focar na correção dos bugs da versão do app que esta na loja.
