### ISSUE TITLE
[Login] Permitir login com campo senha contendo caracteres especiais

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#316]
## User Story

**COMO** usuário do app
**QUERO** que o app aceite minha senha contendo caracteres especiais
**PARA** que eu possa utilizar senhas seguras ao realizar login no app

## Descrição
As regras de criação de senha atuais devem aceitar números, letras e caracteres especiais, conforme anexo abaixo.
![image](https://github.com/Is-It-Safe/mobile/assets/136942442/265759a6-91fb-43c8-bece-ac76f3ad0661)

Dito isto, a tela de login do app deve aceitar senhas de acordo com as regras definidas na criação de senha.

## Critério de Aceite

- [ ] Aceitar senhas com que contenham caracteres especiais, independente da quantidade e da posição que os caracteres sejam informados no campo de senha.

## Cenários de Teste

- [ ]  **Cenário:** Login com senha onde o primeiro caractere é especial
**Dado** que esteja na tela de login
**Quando** informar uma senha que atenda as regras definidas na criação da senha
**E** o primeiro caractere informado no campo for um caractere especial
**Então** o app deve permitir que seja realizado o login

- [ ]  **Cenário:** Login com senha que contem vários caracteres especiais
**Dado** que esteja na tela de login
**Quando** a senha informada possuir um ou mais caracteres especiais
**Então** o app deve permitir que seja realizado o login

- [ ]  **Cenário:** Login com senha que não contem caractere especial
**Dado** que esteja na tela de login
**Quando** a senha informada não possuir caractere especial
**Então** o app não deve permitir que o login seja realizado
**E** o usuário deve receber um feedback informando que a senha informada não atende as regras necessárias

## Informações Adicionais

Evidências do problema encontrado:

Campo de senha da tela de login do app não aceita a senha quando o primeiro caractere informado no campo é um caractere especial.

![image](https://github.com/Is-It-Safe/mobile/assets/136942442/01a02ae6-2345-42ab-8073-e132f7b9058d)

https://github.com/Is-It-Safe/mobile/assets/136942442/d128a47b-1893-49db-a1f8-af1bb3c28a3e

**Comment by bruno-luzardi** [comment]
![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/08fab381-ff5a-4d0b-97d6-2298e49f6502)

**Comment by flaviomelodev** [comment]
Alterado o regex de senha para aceitar símbolos em qualquer momento

O que foi feito?
- Acrescentei novo regex: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[$*&@#])[0-9a-zA-Z$*&@#]{8,}$
- Mudança do texto de informações de criação de senha


Tipo de Mudança:
[x] bug

Validações:

![Image](https://github.com/Is-It-Safe/mobile/assets/58519231/5dceb388-992b-43a9-92d1-42a0d6aa3f68)
![Image](https://github.com/Is-It-Safe/mobile/assets/58519231/86038c84-fce1-4475-87a2-19935c9515a0)

**Comment by bruno-luzardi** [comment]
@flaviomelodev  @yllo-luis 
Realizei alguns testes e encontrei um problema, pois o botão de login só esta sendo habilitado quando a senha contém um caractere maiúsculo.
As regras de criação de senha estão em anexo na descrição do card, favor verificar e ajustar.

Evidência do teste realizado.




https://github.com/Is-It-Safe/mobile/assets/136942442/bcaa1ebd-b8dd-4ad6-88b2-c00b0d2435fa

**Comment by flaviomelodev** [comment]
Campo de criar senha não obriga mais letra maiúscula

**Comment by bruno-luzardi** [comment]
@flaviomelodev preciso de uma apk no ambiente de testes para validar a correção realizada.

**Comment by bruno-luzardi** [comment]
@flaviomelodev, pelos testes que fiz ainda não esta ok, pois existem senhas que não estão sendo aceitas e consequentemente não habilitam o botão de login.

Vou deixar abaixo algumas senhas que utilizei nos testes.
cD9*4;7I
n926#J%$

**Comment by flaviomelodev** [comment]
ajustei o regex e agora aceita todos os símbolos

**Comment by bruno-luzardi** [comment]
@flaviomelodev  por favor, suba esta correção para o ambiente de PRD.
