### ISSUE TITLE
[BUG] Falha na atualização de dados ao Editar informações pessoais

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#338]
## Descrição do problema
Ao utilizar a tela de edição de informações pessoais estão ocorrendo os seguintes problemas:

- Ao acessar a tela de editar informações pessoais o app não carrega a informação dos campos Orientação Sexual e gênero.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/4061b1ca-98d2-45b4-8491-8b0baac230c4)

- Ao editar dados de Orientação Sexual e gênero o botão Atualizar informações não é habilitado, sendo necessário editar a informação de outros campos na tela para que o botão seja habilitado, só assim é possível salvar alguma alteração realizada nos campos Orientação Sexual e gênero.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/910c5a97-5457-476c-acf3-9d5f135128c9)

- Ao editar informações do campo Usuário o campo fica com destaque/contorno vermelho.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/f1e08ac1-520a-4962-a6cb-71a5d9018425)

- Ao atualizar os dados salvos e voltar a tela de Informações Pessoais os campos não são atualizados com a informação inserida na tela de Editar informações pessoais.

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/9aef8b0d-0d06-40b7-a4a6-07744ff9dd38)

## Etapas para reproduzir (se aplicável)

1. Logar no app
2. Acessar o menu principal
3. Acessar a opção Minha Conta
4. Acessar a opção Editar perfil
5. Editar informações na tela
6. Atualizar as informações alteradas
7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário.

## Comportamento esperado

- Ao abrir a tela de edição da conta a informação de todos os campos devem ser exibidas na tela para o usuário.

- Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados.

- Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.
 
- Ao salvar as alterações realizadas, quando o app voltar a tela anterior as atualizações realizadas devem ser refletidas na tela Minha Conta.

## Capturas de tela ou logs

O vídeo abaixo apresenta todos os bugs listados neste card.

https://github.com/Is-It-Safe/mobile/assets/136942442/f6f6a433-39ea-4802-9baf-1718834bb8e0

## Ambiente

Sistema operacional: Android
Navegador (se aplicável): N/A
Versão do app: v1.0.7+14
Ambiente: PRD

## Cenários de Teste

- [ ]  Cenário: Acessando a tela de Editar Conta
**Dado** que deseje editar dados da conta
**E** acesse a tela Editar Conta
**E** todos os campos da tela sejam abertos e carregados com a última informação salva no cadastro
**Quando** desistir de editar os dados da conta
**E** fechar a tela Editar Conta
**Então** o sistema deverá manter os dados atuais
**E** voltar a tela de perfil

- [ ]  Cenário: Editar informações da conta
**Dado** que deseja editar dados da conta
**Quando** acessar a tela Editar Conta
**Então** todos os campos da tela devem ser abertos e carregados com a última informação salva no cadastro
**E** permitir que qualquer dado seja alterado

- [ ]  Cenário: Salvar edição de informações da conta
**Dado** que deseja editar dados da conta
**E** acesse a tela Editar Conta
**Quando** editar qualquer informação da conta
**Então** o botão Atualizar Informações deverá ser habilitado
**E** permitir que a alteração realizada seja salva

## Definições de Pronto:

- [ ] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [ ] Todos os critérios de aceite foram atendidos.
- [ ] O feedback ao usuário é claro e informativo.
- [ ] A validação dos campos é feita de acordo com os critérios especificados.
- [ ] O aplicativo atende aos requisitos de formatação e validação de dados.
- [ ] A documentação da funcionalidade foi criada ou atualizada.
- [ ] A implementação segue a paleta de cores e padrão do projeto.
- [ ] A funcionalidade possui os testes unitários.

**Comment by Rodrigo-Motta-QA** [comment]
@bruno-luzardi 
Nas definições de pronto existem 2 tópicos que impedem que ao testar seja finalizada a tarefa, visto que depende de processos anteriores aos testes.


![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/9e5c1634-6c62-4ba5-8dbd-c2149409f4a8)

**Comment by bruno-luzardi** [comment]
@Rodrigo-Motta-QA  atualizei o definição de pronto do card, pode seguir com os testes focando na resolução dos problemas apontados.

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-002                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Editar informações da conta. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | PASSOU  |
| **Resultado Encontrado**    | A aplicação permite que qualquer dado seja alterado. |

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-003                               |
|--------------------------|----------------------------------------|
| **Descrição**               | Salvar edição de informações da conta. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não habilita o botão de atualizar informações e apenas os combos de Orientação sexual e Gênero forem alterados. |

Evidência:



https://github.com/Is-It-Safe/mobile/assets/125081870/368c564d-5b87-4e70-9627-8e6bb51721bd

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-001.1                                 |
|--------------------------|----------------------------------------|
| **Descrição**               | Acessando a tela de Editar Conta. |
| **Plataforma utilizada para o teste**   |  Apk gerada pela branch #468  |
| **Versão utilizada para o teste** | 1.0.8 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário.|

Evidência:


https://github.com/Is-It-Safe/mobile/assets/125081870/a1390040-5cc4-44d6-9536-d781c913952e

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-002.1                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Editar informações da conta. |
| **Plataforma utilizada para o teste**   |  Apk gerada pela branch #468  |
| **Versão utilizada para o teste** | 1.0.8 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário. |

Evidencia:


https://github.com/Is-It-Safe/mobile/assets/125081870/c7fa551b-eb11-47fd-ab88-408c7136d5a5

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-002.1                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Editar informações da conta. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 via App tester / app distribution firebase |
| **Versão utilizada para o teste** | 1.0.27-qa |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário. |

Evidencia:



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/80df2057-9cca-4f9f-92e1-42829c54edf6)



https://github.com/Is-It-Safe/mobile/assets/125081870/1f0a35ef-dcc7-48a8-abc4-ca9d5d0a9458

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-003.2                          |
|--------------------------|----------------------------------------|
| **Descrição**               | Salvar edição de informações da conta. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 via App tester / app distribution firebase |
| **Versão utilizada para o teste** | 1.0.27-qa |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário. |

Evidência:



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/c6c8d9c5-72d6-41f1-a017-7900f38bbbd1)



https://github.com/Is-It-Safe/mobile/assets/125081870/6016a32d-fe72-4915-8105-110befcb70f5

**Comment by bruno-luzardi** [comment]
@Rodrigo-Motta-QA  favor realizar os testes com a nova versão disponibilizada pelo @Tharsisboamorte .

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-001.2                                 |
|--------------------------|----------------------------------------|
| **Descrição**               | Acessando a tela de Editar Conta. |
| **Plataforma utilizada para o teste**   |  Apk enviada pelo Dev @Tharsisboamorte   |
| **Versão utilizada para o teste** | 1.0.8 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário.|

Evidência:

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-002.2                               |
|--------------------------|----------------------------------------|
| **Descrição**               | Editar informações da conta. |
| **Plataforma utilizada para o teste**   |  Apk enviada pelo Dev @Tharsisboamorte  |
| **Versão utilizada para o teste** | 1.0.8 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário. |

Evidencia:

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #338-003.2                   |
|--------------------------|----------------------------------------|
| **Descrição**               | Salvar edição de informações da conta. |
| **Plataforma utilizada para o teste**   |  Apk enviada pelo Dev @Tharsisboamorte   |
| **Versão utilizada para o teste** | 1.0.8 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
|                                      | 2. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Logar no app          |
|                                         | 2. Acessar o menu principal |
|                                         | 3. Acessar a opção Minha Conta  |
|                                         | 4. Acessar a opção Editar perfil    |
|                                         | 5.  Editar informações na tela  |
|                                         | 6.  Atualizar as informações alteradas |
|                                         | 7. Voltar ao menu anterior e verificar se foram refletidas as alterações realizadas na conta do usuário. |
| **Dados de Entrada**     |  E-mail e senha válidos|
| **Resultados Esperados**  | Ao abrir a tela de edição da conta, a informação de todos os campos devem ser exibidas na tela para o usuário.   |
|                                           | Ao editar alguma informação da conta do usuário, deve ser possível salvar as alterações realizadas, independente da quantidade de campos que tenham sido alterados. |
|                                          |  Ao editar informações, caso não exista nenhum erro nas informações alteradas ou nenhuma validação pendente, os campos não precisam ficar destacados em vermelho, para não representar "erros" no fluxo.  |
| **Critérios de Aceitação**| Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta.  |
| **Pós-condições**         | Ao salvar as alterações realizadas, quando o app voltar a tela anterior, as atualizações realizadas devem ser refletidas na tela Minha Conta. |
| **Resultado do teste**  | FALHOU  |
| **Resultado Encontrado**    | A aplicação não permite salvar alterações no perfil do usuário. |

Evidência:
