### ISSUE TITLE
Atualizar mensagem  com as regras de criação de senha na tela de cadastro

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#348]
Precisamos ajustar o design/mensagem da tela de cadastro atual para que as regras de criação de senha fiquem no mesmo padrão dos demais fluxos.

Imagem da Tela de cadastro de senha:

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/2718ef78-5351-49c3-9cd0-23ec307099db)

Segue abaixo uma imagem para servir de referência de como esta o design/mensagem das regras de criação de senha nos fluxos atuais:

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/228cad50-e0f1-42ec-930b-ab368f611744)

**Comment by bruno-luzardi** [comment]
Esta alteração servirá de referência para implementação da us: https://github.com/Is-It-Safe/mobile/issues/274

**Comment by jessicacfd** [comment]
![Image](https://github.com/Is-It-Safe/mobile/assets/56539875/f695c44a-8171-4574-97fe-325c7acdeb60)
