### ISSUE TITLE
Ajustar feedback ao usuário após cadastro de local

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#349]
## Descrição
**COMO** usuário do aplicativo
**QUERO** receber um feedback após cadastrar um local
**PARA** que fique claro que os locais cadastrados no app passam passam por um processo antes de serem exibidos no app

## Critério de Aceite

- [x] O feedback exibido deve deixar claro ao usuário que o local cadastrado passa por um processo antes de ser exibido no app.
- [x] Ao exibir o feedback o aplicativo exibe um botão denominado "Explorar outros locais", após o usuário clicar no botão, o app fecha o modal e retorna para a tela de busca.
- [x] O app deverá voltar para a tela de busca em seu estado inicial, ou seja, com o campo de pesquisa "limpo" e sem a opção de "Adicionar local" exibida na tela.
- [x] Seguir o design do figma:
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=6137-9283&mode=design&t=XMkXJlrn6d0T1bMd-4

## Cenários de Teste

- [ ] Cenário: Exibindo feedback ao usuário
**Dado** que seja realizado o cadastro de um local no app
**Quando** o usuário finalizar a inclusão do local
**Então** o aplicativo deve fornecer um feedback para o usuário
**E** deve ficar claro que o local cadastrado precisa passar por um processo de aprovação
**E** o aplicativo deverá voltar a tela de busca
**E** o campo de pesquisa deverá estar vazio
**E** não deverá deverá ser exibida a opção "adicionar local" na tela de busca

## Informações Adicionais
Após exibir o feedback o aplicativo deverá voltar na tela de busca na condição abaixo:

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/fa3c1d2c-ffb0-4121-92ea-6de2d04780a2)

**Comment by Rodrigo-Motta-QA** [comment]
### Documento de Teste - Cadastro de Local no Aplicativo

### Cenário de Teste: Exibindo feedback ao usuário

### Objetivo:
Verificar se o aplicativo fornece um feedback claro ao usuário após cadastrar um local, e se o retorno para a tela de busca está correto, conforme os critérios de aceite e o design do Figma.

### Dados de Teste:
Teste executado na versão app-debug

### Passos Executados:

### Cadastro de Local:

### Acesse o aplicativo.

- [ ] Navegue até a opção de cadastrar um novo local.
- [ ] Complete os campos necessários para cadastrar o local.
- [ ] Finalize o processo de cadastro.

### Verificação do Feedback:

- [ ] Verifique se o feedback é exibido corretamente após o cadastro.
- [ ] Confirme se o feedback deixa claro que o local cadastrado está passando por um processo de aprovação.
- [ ] Botão "Explorar Outros Locais":

### Certifique-se de que o modal de feedback exibe um botão com a etiqueta "Explorar Outros Locais".

- [ ] Clique no botão "Explorar Outros Locais".
- [ ] Fechamento do Modal:

### Verifique se o modal é fechado corretamente após clicar no botão "Explorar Outros Locais".

- [ ] Retorno para a Tela de Busca:

### Confira se a aplicação retorna para a tela de busca após fechar o modal.

- [ ] Estado Inicial da Tela de Busca:

### Verifique se a tela de busca está no seu estado inicial.

- [ ] Confirme se o campo de pesquisa está vazio.
- [ ] Certifique-se de que a opção "Adicionar Local" não é exibida.

### Critérios de Aceite:

- [ ] O feedback é claro e informa que o local cadastrado passa por um processo de aprovação.
- [ ] O modal exibe corretamente o botão "Explorar Outros Locais".
- [ ] Clicar no botão "Explorar Outros Locais" fecha o modal.
- [ ] A aplicação retorna para a tela de busca após fechar o modal.
- [ ] O campo de pesquisa está vazio na tela de busca.
- [ ] A opção "Adicionar Local" não é exibida na tela de busca.

### Resultado do Teste:
Teste foi bem-sucedido.

### Observações e Melhorias:
Tela apresentada corresponde ao design do Figma com ressalvas.
O ícone de sucesso está diferente do figma.

### Responsável pelo Teste:
Rodrigo Motta

### Data do Teste:
12/12/2023 09:32

### Ambiente de Teste:
Windows 10
Genymotion 3.5.1 (Android)

### Evidencias

### Tela de feedback
![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/46cc6a3e-7298-4743-99ab-8b71ebc99004)

### Tela de retorno a procura após feedback

![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/221533af-523c-4c16-b861-24342db5fe96)

**Comment by Rodrigo-Motta-QA** [comment]
### Documento de Teste - Cadastro de Local no Aplicativo

### Cenário de Teste: Exibindo feedback ao usuário

### Objetivo:
Verificar se o aplicativo fornece um feedback claro ao usuário após cadastrar um local, e se o retorno para a tela de busca está correto, conforme os critérios de aceite e o design do Figma.

### Dados de Teste:
Teste executado na versão app-release

### Passos Executados:

### Cadastro de Local:

### Acesse o aplicativo.

- [x] Navegue até a opção de cadastrar um novo local.
- [x] Complete os campos necessários para cadastrar o local.
- [x] Finalize o processo de cadastro.

### Verificação do Feedback:

- [x] Verifique se o feedback é exibido corretamente após o cadastro.
- [x] Confirme se o feedback deixa claro que o local cadastrado está passando por um processo de aprovação.
- [x] Botão "Explorar Outros Locais":

### Certifique-se de que o modal de feedback exibe um botão com a etiqueta "Explorar Outros Locais".

- [x] Clique no botão "Explorar Outros Locais".
- [x] Fechamento do Modal:

### Verifique se o modal é fechado corretamente após clicar no botão "Explorar Outros Locais".

- [x] Retorno para a Tela de Busca:

### Confira se a aplicação retorna para a tela de busca após fechar o modal.

- [x] Estado Inicial da Tela de Busca:

### Verifique se a tela de busca está no seu estado inicial.

- [x] Confirme se o campo de pesquisa está vazio.
- [x] Certifique-se de que a opção "Adicionar Local" não é exibida.

### Critérios de Aceite:

- [x] O feedback é claro e informa que o local cadastrado passa por um processo de aprovação.
- [x] O modal exibe corretamente o botão "Explorar Outros Locais".
- [x] Clicar no botão "Explorar Outros Locais" fecha o modal.
- [x] A aplicação retorna para a tela de busca após fechar o modal.
- [x] O campo de pesquisa está vazio na tela de busca.
- [x] A opção "Adicionar Local" não é exibida na tela de busca.

### Resultado do Teste:
Teste foi bem-sucedido.

### Observações e Melhorias:
Tela apresentada corresponde ao design do Figma com ressalvas.
O ícone de sucesso está diferente do figma.

### Responsável pelo Teste:
Rodrigo Motta

### Data do Teste:
12/12/2023 09:32

### Ambiente de Teste:
Windows 10
Genymotion 3.5.1 (Android)

### Evidencias

### Tela de feedback
![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/46cc6a3e-7298-4743-99ab-8b71ebc99004)

### Tela de retorno a procura após feedback

![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/221533af-523c-4c16-b861-24342db5fe96)

**Comment by Rodrigo-Motta-QA** [comment]
Inconsistência apresentadas nas telas do aplicativo via emulador e no aplicativo instalado localmente, e a tela difere em muito do padrão solicitado pelo Figma Tanto em formato, ícone e texto apresentado.
Link Notion: [](https://www.notion.so/isitsafe/CT-349-01-40f69c3e28304b35874c4e008c72c77e)

**Comment by Rodrigo-Motta-QA** [comment]
| **ID do Caso de Teste** | CT#349-002                                  |
|--------------------------|----------------------------------------|
| **Descrição**               | Ajustar feedback ao usuário após cadastro de local. |
| **Pré-condições**        | 1. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Fornecer e-mail válido           |
|                                         | 2. Fornecer senha valida         |
|                                         | 3. Clicar em login  |
|                                         | 4. Clicar em menu principal    |
|                                         | 5.  Clicar em adicionar local  |
|                                         | 5.  Fornecer as informações solicitadas para adição de um novo local. |
|                                         | 6. Clicar em adicionar local |
| **Dados de Entrada**      | Nome do local, CEP, Endereço, Tipo do local.  |
| **Resultado Esperado**    | É esperado que o local seja adicionado com sucesso e que a mensagem de feedback corresponda ao padrão a ser seguido pelo Figma.   |
| **Critérios de Aceitação**| 1. O feedback é claro e informa que o local cadastrado passa por um processo de aprovação.  |
|                                          | 2. O modal exibe corretamente o botão "Explorar Outros Locais". |
|                                          | 3. Clicar no botão "Explorar Outros Locais" fecha o modal. |
|                                          | 4. A aplicação retorna para a tela de busca após fechar o modal. |
|                                          | 5. O campo de pesquisa está vazio na tela de busca.|
|                                          | 6. A opção "Adicionar Local" não é exibida na tela de busca. |
| **Pós-condições**         | A aplicação retorna para a tela de busca após fechar o modal. |
| **Resultado do teste**  | Passou  |
| **Resultado Encontrado**    |      |
| **Sugestão de Melhorias ** | O icone de ok está menor do que o indicado pelo Figma.      |

Evidência:


![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/46c4abb3-99f6-4e72-b67d-534d5ca955cb)
