### ISSUE TITLE
Analisar estrutura de funcionalidades no app

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#350]
##Descrição
**_Esta task é apenas de análise, não deverá ser desenvolvido e nem alterado nada na aplicação atual._**

Esta task foi criada para que seja feita uma analise detalhada no aplicativo afim de entender se algumas funcionalidades que estamos planejando já existem no app e atualmente estariam apenas "desabilitadas".
Existem indícios de que estas funcionalidades já haviam sido implementadas no passada e que foram desabilitadas por conta de bugs.

## Necessidade

- [x] Analisar se existem telas ou código fonte no aplicativo relacionado as funcionalidades listadas abaixo:

1. Alteração de e-mail
2. Alteração de senha
3. Desativação de conta no app

- [x] Caso exista alguma tela ou código fonte relacionado a estas funcionalidades, será preciso analisar e documentar abaixo se podemos reutilizar algo que existe ou se teremos que implementar do zero. Esta documentação servirá de base para a criação do backlog relacionado a estas funcionalidades.

**Comment by Tharsisboamorte** [comment]
As telas de mudança de e-mail, senha e desativar já existem, porém nenhuma delas possui fluxo no app ainda, não tem como acessa-las, ou seja, falta um botão no menu drawer para acessar configurações.

## Troca de senha
As duas telas estão prontas, uma pedindo a senha atual e a outra pedindo a nova senha com os dois campos de texto. Itens que podemos reaproveitar são:

- O campo de texto
- Botão de ação 
- Modal de sucesso que está presente em outras telas
- Mensagem de sucesso

Não possuimos:

- Indicador de página
- Textos explicativos

## Trocar Email
Mesma necessidade de implementar uma segunda tela, para aceitar o código de verificação, também não tem a necessidade de um segundo botão para o cancelamento do processo, já que o botão de backpressed já daria conta disso, portanto não da pra reaproveitar ele, também não é possível reaproveitar o botão que levaria para próxima tela, já que o novo design é um botão com um icone. A única coisa que da pra reaproveitar na atual tela são:

- Texto do AppBar
- Texto da headline

## Desativar conta
Na página de desativar conta apenas o botão e o titulo da tela podem ser reaproveitado, mas também deve-se mudar o nome e a utilização dele, de resto não temos nenhum dos novos itens, inclusive a uma necessidade de adicionar o modal que pede a senha e a confirmação dela.
