### ISSUE TITLE
Configurar CI/CD do aplicativo para geração automatica de apk nos ambientes

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#356]
Ajustar a esteira de CI/CD para que gere automaticamente a apk do app.

Para buildar a apk:

    Apontando para desenv:

flutter build apk -t lib/main_dev.dart --release

    Apontando para produção:

flutter build apk -t lib/main.dart --release

**Comment by bruno-luzardi** [comment]
Oi, @LaysonEduardo, já foi finalizada a documentação desta demanda ?

**Comment by LaysonEduardo** [comment]
Foi sim, é possível acessa-la em:
https://www.notion.so/isitsafe/Como-gerar-um-APK-para-teste-usando-as-actions-do-Github-22593da69ffe48cbbefb3c7aa9b53c30?pvs=4

Em dom., 5 de nov. de 2023 às 18:04, bruno-luzardi ***@***.***>
escreveu:

**Comment by bruno-luzardi** [comment]
Neste caso vou encerrar o card, pois entendo que estava pendente apenas de finalizar a documentação.
