### ISSUE TITLE
Analisar arquitetura atual para envio de fotos ao cadastrar locais

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#375]
##Descrição
**_Esta task é apenas de análise, não deverá ser desenvolvido e nem alterado nada na aplicação atual._**

Atualmente existe uma limitação no backend/api que só permite a adição de uma imagem por local cadastrado no app ou no dashboard.
Esta limitação foi identificada em uma call realizada com os desenvolvedores do dashboard quando estavam trabalhando para permitir que o dashboard cadastra-se um local com até 4 imagens do local.

## Necessidade

- [x] Avaliar e documentar porque a estrutura atual só permite salvar uma imagem por local cadastrado.
- [x] Avaliar e documentar, de acordo com a complexidade e esforço, se é viável alterar a estrutura atual ou se seria melhor criarmos uma nova estrutura que permita salvar mais imagens ao cadastrar um local.
- Qual o esforço de alteração da estrutura atual ?
- Qual o esforço e complexidade em criarmos uma nova estrutura ?

- [x] Avaliar se é possível que a estrutura fique em um formato que permita salvar quantas imagens quisermos de um local ou se mesmo com alterações na estrutura teríamos algum limite na quantidade de imagens salvas ao cadastrar um local no app ou no dash.

## Pontos de atenção
Atualmente existem duas formas de adicionar um local e devemos considerar que ambos os sistemas precisam ser contemplados por esta mudança.

-  Cadastrar o local direto no aplicativo, que faz o envio do local para o dashboard para passar pelo processo de aprovação, neste fluxo as imagens enviadas pelo app serão recebidas e exibidas no dashboard.
- Cadastrar o local diretamente no dashboard, permitindo que sejam anexadas as imagens do local.

**Comment by ValterGabriell** [comment]
E estrutura permite salvar apenas 1 foto por vez porque o método foi criado para receber apenas uma foto ao salvar um local.

Qual o esforço de alteração da estrutura atual ?
R- Precisaria alterar a estrutura do banco de dados, esse seria o maior esforço e mudança com maior impacto, pois para receber mais imagens precisaríamos receber como uma lista, mas atualmente o banco guarda apenas 1 imagem, então uma atualização precisaria ser feita para isso.

Qual o esforço e complexidade em criarmos uma nova estrutura ?
R- Adicionar um novo campo na estrutura pode ser considerado menos intrusivo e requer menos esforço em comparação com a atualização de um campo existente, especialmente se a compatibilidade com as versões anteriores é uma preocupação.

**Comment by ValterGabriell** [comment]
![1 drawio_1](https://github.com/Is-It-Safe/mobile/assets/63808405/38062177-b653-40ad-89ca-e77f2ab25d5b)

**Comment by ValterGabriell** [comment]
Cada valor inserido na tabela de imagens por locação terá uma unica imagem linkada ao estabelecimento, em caso de varias imagens será feita a busca por estabelecimento id e isso retornará todas as imagens que o estabeleciimento possui.
