### ISSUE TITLE
Aumentar tempo de validade do link de ativação de conta

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#378]
## User Story

**COMO** novo usuário cadastrado no aplicativo
**DESEJO** que o link de validação de conta tenha um tempo maior de validade
**PARA** que eu possa validar minha conta antes do link expirar

## Descrição

Alterar o tempo de validade do link de ativação de conta de 5 minutos para 24 horas.

## Critério de Aceite

- [ ] O link de ativação de conta enviado logo após o cadastro deverá ter o tempo de validade de 24 horas.

## Cenários de Teste

- [ ] **Cenário**: 
**Dado** 
**Quando** 
**Então**

**Comment by ValterGabriell** [comment]
Valter Gabriel
Foi realizado a mudanca no tempo de expiração do link para ativação de conta de 5 minutos para 24 horas.
