### ISSUE TITLE
[Cadastro e Ativação de Conta] Criar estrutura para enviar e salvar o código de ativação de usuário

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#384]
# Descrição

Esta tarefa diz respeito à implementação do envio e armazenamento de um código de 4 dígitos para ativação de usuários. Durante o processo de registro, um código de ativação será gerado, enviado por e-mail ao usuário e armazenado de forma segura. A segurança será garantida por meio da criptografia do código antes de armazená-lo no banco de dados.

## Detalhamento Técnico

Envio do Código de Ativação:

- [x] Um código de ativação de 4 dígitos será gerado durante o processo de registro do usuário.

- [x] Este código será enviado automaticamente para o endereço de e-mail fornecido pelo usuário no momento do registro.

- [x] O e-mail de ativação conterá instruções claras sobre como proceder com a ativação da conta.

## Armazenamento Seguro:

Antes de ser armazenado no banco de dados, o código de ativação será submetido a um processo de criptografia.

Critério de Aceite

- [x]  O usuário deve receber um código de ativação com 4 dígitos em seu e-mail após o registro.

- [x]  O código de ativação deve ser criptografado antes de ser armazenado no banco de dados.

- [x]  O código criptografado deve ser armazenado na tabela de usuários.

## Definições de Pronto:

- [x] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [x] Todas os critérios de aceite foram atendidos.
- [x] A validação dos campos é feita de acordo com os critérios especificados.
- [x] O aplicativo atende aos requisitos de formatação e validação de dados.
- [x] Documentar as entregas (endpoints, etc)

**Comment by ValterGabriell** [comment]
Link da documentação das alterações: https://www.notion.so/isitsafe/Documenta-o-novo-Fluxo-de-Cadastro-a971b666f65c456f816923da1884ad09?pvs=4

**Comment by Rodrigo-Motta-QA** [comment]
Cenário testado e documentado conforme definido.
Link Notion: https://www.notion.so/isitsafe/f68beb8be9dc43c1b31bdceb83a8cbba?v=00ee94df9867441bb1b56698a385898c
