### ISSUE TITLE
[Cadastro e Ativação de Conta] Validar código de ativação de conta enviado por e-mail

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#385]
# Descrição da Tarefa:
Esta tarefa tem como objetivo implementar a validação de um código de ativação criptografado para permitir o cadastro de um usuário. O processo de validação consiste em comparar o código criptografado inserido pelo usuário com o código criptografado armazenado no banco de dados. Se os códigos coincidirem, o fluxo de cadastro continua. Caso contrário, o fluxo é interrompido.

## Detalhamento Técnico:

Validação do Código Criptografado:

O usuário deve inserir o código de ativação.

 Ao chamar o serviço de validação, o código inserido pelo usuário será criptografado.

O código criptografado será comparado com o código criptografado armazenado no banco de dados.

 Se os códigos coincidirem, o processo de cadastro continuará.

Se os códigos não coincidirem, o processo de cadastro será interrompido.

## Critério de Aceite:

- [x] O usuário deve ser capaz de inserir o código de ativação durante o processo de cadastro.

- [x] O código inserido pelo usuário deve ser criptografado antes da comparação.

- [x] O código criptografado inserido deve ser comparado com o código criptografado armazenado no banco de dados.

- [x] Se os códigos coincidirem, o cadastro do usuário deve ser permitido.

- [x] Se os códigos não coincidirem, o processo de cadastro deve ser interrompido.

## Cenários de Teste:

Cenário:
Dado que um usuário esteja se registrando e recebeu um código de ativação
Quando ele inserir o código de ativação corretamente durante o cadastro
Então seu cadastro deve ser concluído com sucesso

Cenário:
Dado que um usuário esteja se registrando e recebeu um código de ativação
Quando ele inserir um código de ativação incorreto durante o cadastro
Então seu cadastro deve ser interrompido e uma mensagem de erro deve ser exibida

## Definições de Pronto:

- [x] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [x] Todas os critérios de aceite foram atendidos.
- [x] A validação dos campos é feita de acordo com os critérios especificados.
- [x] O aplicativo atende aos requisitos de formatação e validação de dados.
- [x] Documentar as entregas (endpoints, etc

**Comment by ValterGabriell** [comment]
No endpoint /is-it-safe/user/save, foi introduzido um novo parâmetro de consulta chamado withFourConfirmationCode. Agora, a URL de salvamento de usuário evoluiu de "/is-it-safe/user/save" para "/is-it-safe/user/save?withFourConfirmationCode=true". O valor true ou false deste parâmetro define se a ativação de conta por meio de um código de 4 dígitos estará habilitada, onde true indica habilitada e false indica desabilitada.

Formato JSON para Ativação

O JSON a ser fornecido para a ativação de conta segue o seguinte formato:
{
    "birthDate": "21/11/1999",
    "name": "James McGuill",
    "email": "email@gmail.com",
    "nickname": "nick"
}

## Validação do código

O endpoint responsável pela verificação do código da conta agora é "/is-it-safe/verify-code?code=X". No fluxo anterior, esse endpoint era acionado ao clicar no link de ativação recebido por e-mail. No novo fluxo, esse endpoint deve ser acessado ao clicar no botão "Prosseguir" para validar a conta do usuário. Um resultado será exibido, indicando o sucesso ou a falta de validação.

## Reenvio do Código de 4 Dígitos

Para reenviar o código de 4 dígitos, utilize o endpoint /is-it-safe/resend-code. O endereço de e-mail deve ser fornecido no corpo da solicitação, como no exemplo abaixo:

{
    "email": "email@gmail.com"
}

## Ativação da Conta

Após a validação bem-sucedida do código, a conta do usuário pode ser ativada utilizando o endpoint /is-it-safe/user/active-account?userId=X. Passando a senha no corpo da requisição:

{
	"password":"12345567"
}

A senha encodada será salva no banco e o usuário será ativo no sistema

**Comment by williampezz** [comment]
Em teste!

**Comment by williampezz** [comment]
Cenários validados conforme evidencia em anexo:



[US385.zip](https://github.com/Is-It-Safe/mobile/files/13641777/US385.zip)

**Comment by Rodrigo-Motta-QA** [comment]
Cenário testado e documentado conforme definido.
Link Notion: https://www.notion.so/isitsafe/1ab9013f8c35409db9d8ac8b291ab181?v=f4ce2cc051554f3ab86f702e5833684b
