### ISSUE TITLE
Criar validação do campo de senha e confirmação de senha no fluxo de cadastro

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#391]
## User Story

**COMO** usuário me cadastrando no aplicativo
**DESEJO** que exista uma validação nos campos senha e confirmação de senha
**PARA** garantir a consistência das informações inseridas durante a criação da senha

## Descrição
Atualmente, no fluxo de cadastro, a validação existente entre os campos senha e confirmação de senha esta com problemas, não garantindo a consistência das informações inseridas pelo usuário e gerando falhas sobre o momento exato de habilitar o botão Cadastrar.
Além disso, é possível finalizar o cadastro com informações diferentes nos campos senha e confirmação de senha.

Necessário ajustar as regras de validação dos campos senha e confirmação de senha para garantir a consistência dos dados inseridos e habilitar o botão de Cadastro no momento correto.

## Critério de Aceite

- [x] As informações inseridas nos campos senha e confirmação senha devem ser iguais para que o cadastro seja realizado.
- [ ] O botão Cadastrar só deve ser habilitado quando a senha e confirmação de senha forem iguais.
- [ ] O usuário deverá receber um feedback quando as informações dos campos senha e confirmação de senha forem diferentes.
- [ ] Não deverá ser permitido realizar o cadastro com informações diferentes nos campos senha e confirmação de senha.
- [ ] O usuário deverá ajustar as informações dos campos senha e confirmação de senha antes de finalizar o cadastro.
- [ ] Seguir este figma na implementação dos feedbacks e regras de validação:
https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=4557-7979&mode=design&t=fsfPcIUQIiQ3HnvN-4

## Cenários de Teste

- [ ]  Cenário: Solicitando link para reset de senha
**Dado** que esqueça minha senha
**Quando** eu realizar o fluxo de reset de senha
**Então** devo receber um e-mail para realizar fazer o reset da senha
**E** o e-mail deverá estar no novo layout
**E** deverá conter as informações de: nome do usuário, texto informativo sobre o assunto do e-mail, informação sobre o tempo de validade do link de reset de senha, link para realizar o reset de senha e o e-mail de contato do suporte.

## Definições de Pronto:

- [ ] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [ ] Todas os critérios de aceite foram atendidos.
- [ ] O feedback ao usuário é claro e informativo.
- [ ] A validação dos campos é feita de acordo com os critérios especificados.
- [ ] O aplicativo atende aos requisitos de formatação e validação de dados.
- [ ] A implementação segue a paleta de cores e padrão do projeto

**Comment by Rodrigo-Motta-QA** [comment]
Cenário testado e documentado conforme definido.
2 incidentes foram encontrados:

1º - É possível realizar o cadastro de usuário sem realizar a marcação do checkbox de termos de udo e condições.
Notion: https://www.notion.so/isitsafe/CT-391-1-06-fc48a4abb0bd408ba679a1c60977c541

2º - O layout do e-mail recebido pelo usuário está em desacordo com o Figma.
Notion: https://www.notion.so/isitsafe/CT-391-2-01-d86064646cda4945b867c342a81a4288

**Comment by bruno-luzardi** [comment]
Para o item 1 foi aberto o bug: https://github.com/Is-It-Safe/mobile/issues/417

**Comment by bruno-luzardi** [comment]
Para o item 2 foi aberta uma task de melhoria: https://github.com/Is-It-Safe/mobile/issues/418
