### ISSUE TITLE
Criar dialogo de texto sobre pedido de localização do usuário

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#392]
## User Story

**COMO** usuário do app
**DESEJO** ter um feedback claro antes de compartilhar minha localização
**PARA** que eu entenda os motivos pelo qual devo permitir o uso de minha localização

## Descrição
Durante a publicação do app para a loja da google um dos motivos pelo qual a publicação foi reprovada na loja é o fato de não estarmos deixando claro para o usuário o motivo pelo qual precisamos que o mesmo permita o uso da sua localização.

Necessário ajustar o diálogo com o usuário deixando claro o motivo pelo qual precisamos que ele permita o uso da sua localização, este dialogo precisa ser antes da tela onde atualmente solicitamos a localização do mesmo.

## Critério de Aceite

- [x] O dialogo de texto deverá aparecer antes da tela onde o usuário compartilha a localização.
- [x] Seguir o design criado no figma:
- [x] https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=6402-8118&mode=design&t=RH71HIJW5AabuGyi-4

## Cenários de Teste

- [ ]  Cenário: 
**Dado** 
**Quando** 
**Então** 

- [ ]  Cenário: 
**Dado** 
**Quando** 
**Então** 

## Definições de Pronto:

- [x] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [x] Todas os critérios de aceite foram atendidos.
- [x] O feedback ao usuário é claro e informativo.
- [x] A validação dos campos é feita de acordo com os critérios especificados.
- [x] O aplicativo atende aos requisitos de formatação e validação de dados.
- [x] A implementação segue a paleta de cores e padrão do projeto

## Informações Adicionais

Artigo citado por Mabel.
https://zopagaduanjr.medium.com/customization-and-localization-of-permissions-in-flutter-f1968dab0943

**Comment by LaysonEduardo** [comment]
Imagem do dialogo referente a explicação da permissão de localização

![Image](https://github.com/Is-It-Safe/mobile/assets/31933025/bf6815f6-3607-4624-967a-7d019d1296c6)

**Comment by bruno-luzardi** [comment]
@LaysonEduardo baixei a apk do pr que vc abriu quando testo o app esta tavando após o login, segue evidência:



https://github.com/Is-It-Safe/mobile/assets/136942442/4c0351a0-eb82-486e-a655-6fdf94b1e6bb

**Comment by bruno-luzardi** [comment]
@LaysonEduardo  baixei a apk do pr que o Flavio abriu após o seu pr e o app não mostra o dialogo, após o login esta indo direto para o pedido de localização.



![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/377abf37-d013-4007-baf5-512ac54a4e54)
