### ISSUE TITLE
App enviar informações do campo endereço para o Dashboard

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#393]
## User Story

**COMO** administrador do dashboard
**DESEJO** receber o endereço de um local cadastrado no app
**PARA** que eu preserve os dados informados pelo usuário ao aprovar um local

## Descrição
Ao cadastrar e salvar um local no app é necessário enviar a informação do campo endereço para o backend para que esta informação possa ser exibida no dashboard.
A informação que o usuário inputar no app deve ser preservada.

Documentação da alteração realizada no backend:
https://www.notion.so/isitsafe/Documenta-o-fluxo-de-grava-o-de-endere-o-API-c186bc37d2334a11822ba0bad25b9e6a?pvs=4

## Critério de Aceite

- [ ] Ao cadastrar um local no app, as informações do campo endereço devem ser preservadas e enviadas para o backend.

## Cenários de Teste

- [ ]  Cenário: Visualizar a informação de endereço de um local no dashboard
**Dado** que eu cadastre um local no app
**E** informe o endereço do local
**Quando** o local for salvo no app
**Então** o app deve enviar a informação do endereço para o backend
**E** esta informação estará disponível no dashboard.

## Definições de Pronto:

- [ ] Todas as funcionalidades descritas acima foram implementadas e testadas.
- [ ] Todas os critérios de aceite foram atendidos.
- [ ] O feedback ao usuário é claro e informativo.
- [ ] A validação dos campos é feita de acordo com os critérios especificados.
- [ ] O aplicativo atende aos requisitos de formatação e validação de dados.
- [ ] A implementação segue a paleta de cores e padrão do projeto

## Informações Adicionais

Ao analisar um problema com o campo endereço nos locais enviados ao dashboard o Valter identificou a seguinte causa do problema:

Cara, o problema de não estar salvando o endereço que o usuario seta no app ta acontecendo pela seguinte razão.
No backend, ele ta esperando apenas 4 campos. Nome do local, cep, o tipo do local (BAR, RESTAURANTE) e uma imagem. No app, temos o input de rua (endereço) lá, porém esse campo não é recebido na requisição devido a isso

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/3e0a15e7-bb69-4139-b893-8d2ba69ee7d0)

Fui olhar o código do aplicativo e notei que na parte que é responsavel por salvar o endereço
ta passando apenas esses campos que lhe informei tbm

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/7387def5-5d93-4f2b-86ad-4c337c3a39c0)

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/b18f008f-ff67-41c4-9f57-3c8dc176106d)

**Comment by Rodrigo-Motta-QA** [comment]
| *ID do Caso de Teste* | CT#393-001                                  |
|--------------------------|----------------------------------------|
| *Descrição*               | App enviar informações do campo endereço para o Dashboard  |
| *Pré-condições*        | 1. Estar logado no App    |
| *Passos de Execução*   | 1. No menu principal clicar e m Adicionar local |
|                                         | 2. Preencher o nome do local   |
|                                         | 3. Preencher o CEP do local  |
|                                         | 4. Preencher o endereço do local    |
|                                         | 5.  Preencher o tipo do local a partir do combo box  |
|                                         | 6.  Clicar em Adicionar Local  |
| *Dados de Entrada*      | São João 677 Centro, Sao Paulo SP |
| *Resultado Esperado*    |  Que as informações inseridas pelo usuário sejam mantidas no dashbord para validação    |
| *Resultado Encontrado*    |  As informações fornecidas pelo app no processo de cadastro de um local são mantidas, porém, existem informações repetidas e informações adicionadas no processo que não foram fornecidas pelo usuário   |
| *Critérios de Aceitação*| 1. Ao cadastrar um local no app, as informações do campo endereço devem ser preservadas e enviadas para o backend. |
| *Pós-condições*         | Usuário permanece na tela de Adicionar local |
| *Resultado do teste*  | Falhou|


![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/f629b101-5ca6-401a-9882-d296738d7ca0)

**Comment by bruno-luzardi** [comment]
Este card será cancelado, iremos tratar esta demanda com o novo layout da tela de cadastro de locais.
