### ISSUE TITLE
Não permitir o uso de espaço no campo usuário

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#410]
## Descrição
No app, atualmente este sendo permitido o uso de espaço no campo de usuário da tela de cadastro.

## Etapas para reproduzir (se aplicável)

1. Abrir o app
2. Clicar em cadastre-se
3. Preencher os campos da tela de cadastro
4. No campo usuário inserir um nome de usuário que contenha espaço

## Comportamento esperado

- [ ] Não permitir o uso de espaço no campo de usuário. Para isso, iremos criar uma validação no campo de usuário que não permita o uso de espaço e caso o usuário insira o espaço o aplicativo deverá dar um feedback ao usuário e não permitir que siga com o cadastro.

## Capturas de tela ou logs

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/0e5f520b-89c2-41f3-acc5-6206f22d6595)

## Ambiente

Sistema operacional: Android
Navegador (se aplicável): N/A
Versão do app: Produção

## Cenários de Teste

- [ ] Cenário: Realizando cadastro com uso de espaço no campo usuário
**Dado** que eu esteja me cadastrando no aplicativo
**Quando** eu preencher o campo usuário
**Então** o aplicativo não deverá permitir o uso de espaço no campo de usuário

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #410-002                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Nome com apenas espaços em branco. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
| **Passos de Execução**   | 1. Fornecer nome do usuário           |
|                                         | 2. Fornecer o "nickName do usuário contendo apenas espaços em branco."  |
|                                         | 3. Preenchimento do campo Pronomes (Opcional)  |
|                                         | 4. Fornecer e-mail válido     |
|                                         | 5.  Fornecer uma senha  |
|                                         | 6.  Fornecer a confirmação da senha. |
|                                         | 7. Aceitar os termos e condições|
|                                         | 8. Clicar em cadastrar.|
| **Dados de Entrada**      | Nome do usuário, nickName usuário contendo apenas espaços em branco, e-mail, senha, confirmação de senha, aceite dos termos e condições.  |
| **Resultado Esperado**    | É esperado que não seja possível realizar cadastro fornecendo um nome de usuário contendo apenas espaços em branco.   |
| **Critérios de Aceitação**| 1. Não permitir o uso de somente espaços em branco no campo de usuário. Para isso, iremos criar uma validação no campo de usuário que não permita o uso de espaço e caso o usuário insira o espaço o aplicativo deverá dar um feedback ao usuário e não permitir que siga com o cadastro.  |
| **Pós-condições**         | A aplicação aguarda nome de usuário seguindo o padrão indicado. |
| **Resultado do teste**  | XXXXXXX  |
| **Resultado Encontrado**    | A aplicação não permite cadastro, utilizando um nome de usuário contendo espaço em branco.    |

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #410-003                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Combinação de espaços em branco no início e no final do nome. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
| **Passos de Execução**   | 1. Fornecer nome do usuário           |
|                                         | 2. Fornecer o "nickName do usuário com uma combinação de espaços em branco no início e no final do nome."  |
|                                         | 3. Preenchimento do campo Pronomes (Opcional)  |
|                                         | 4. Fornecer e-mail válido     |
|                                         | 5.  Fornecer uma senha  |
|                                         | 6.  Fornecer a confirmação da senha. |
|                                         | 7. Aceitar os termos e condições|
|                                         | 8. Clicar em cadastrar.|
| **Dados de Entrada**      | Nome do usuário, nickName usuário com uma combinação de espaços em branco no início e no final do nome, e-mail, senha, confirmação de senha, aceite dos termos e condições.  |
| **Resultado Esperado**    | Teste inserindo espaços em branco no início e/ou final do nome.  |
|                                          | Certifique-se de que o sistema remova espaços em branco desnecessários e processe o nome corretamente.|
| **Critérios de Aceitação**| 1. Não permitir a criação de perfil com uma combinação de espaços em branco no início e no final do nome para o campo de usuário. Para isso, iremos criar uma validação no campo de usuário que não permita o uso de espaço e caso o usuário insira o espaço o aplicativo deverá dar um feedback ao usuário e não permitir que siga com o cadastro.  |
| **Pós-condições**         | A aplicação aguarda nome de usuário seguindo o padrão indicado. |
| **Resultado do teste**  | XXXXXXX  |
| **Resultado Encontrado**    | A aplicação não permite cadastro, utilizando uma combinação de espaços em branco no início e no final do nome.    |

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #410-004                                |
|--------------------------|----------------------------------------|
| **Descrição**               | Combinação de espaços em branco no início e no final do nome. |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
| **Passos de Execução**   | 1. Fornecer nome do usuário           |
|                                         | 2. Fornecer o "nickName do usuário com uma combinação de espaços em branco no início e no final do nome."  |
|                                         | 3. Preenchimento do campo Pronomes (Opcional)  |
|                                         | 4. Fornecer e-mail válido     |
|                                         | 5.  Fornecer uma senha  |
|                                         | 6.  Fornecer a confirmação da senha. |
|                                         | 7. Aceitar os termos e condições|
|                                         | 8. Clicar em cadastrar.|
| **Dados de Entrada**      | Nome do usuário, nickName usuário com uma combinação de espaços em branco no início e no final do nome, e-mail, senha, confirmação de senha, aceite dos termos e condições.  |
| **Resultado Esperado**    | Teste inserindo espaços em branco no início e/ou final do nome.  |
|                                          | Certifique-se de que o sistema remova espaços em branco desnecessários e processe o nome corretamente.|
| **Critérios de Aceitação**| 1. Não permitir a criação de perfil com uma combinação de espaços em branco no início e no final do nome para o campo de usuário. Para isso, iremos criar uma validação no campo de usuário que não permita o uso de espaço e caso o usuário insira o espaço o aplicativo deverá dar um feedback ao usuário e não permitir que siga com o cadastro.  |
| **Pós-condições**         | A aplicação aguarda nome de usuário seguindo o padrão indicado. |
| **Resultado do teste**  | XXXXXXX  |
| **Resultado Encontrado**    | A aplicação não permite cadastro, utilizando uma combinação de espaços em branco no início e no final do nome.    |

**Comment by Rodrigo-Motta-QA** [comment]
|**ID Caso de Teste**     |  CT #410-005                                |
|--------------------------|----------------------------------------|
| **Descrição**               |Nome com espaços no meio e caracteres alfanuméricos válidos e caracteres especiais |
| **Plataforma utilizada para o teste**   |  Xiaomi Poco x3 pro Android11 MIUI 12 |
| **Pré-condições**        | 1. Ter aceso a aplicação.  |
| **Passos de Execução**   | 1. Fornecer nome do usuário           |
|                                         | 2. Fornecer o "nickName do usuário utilizando o comprimento máximo para o campo de usuário."  |
|                                         | 3. Preenchimento do campo Pronomes (Opcional)  |
|                                         | 4. Fornecer e-mail válido     |
|                                         | 5.  Fornecer uma senha  |
|                                         | 6.  Fornecer a confirmação da senha. |
|                                         | 7. Aceitar os termos e condições|
|                                         | 8. Clicar em cadastrar.|
| **Dados de Entrada**      | Nome do usuário, nickName usuário utilizando o comprimento máximo para o campo de usuário, e-mail, senha, confirmação de senha, aceite dos termos e condições.  |
| **Resultado Esperado**    |Teste inserindo um nome que atinja o comprimento máximo permitido, e como se comporta com o estouro do campo.  |
|                                          | Certifique-se de que o sistema lida adequadamente com o comprimento máximo permitido para o nome.|
| **Critérios de Aceitação**| 1. Não permitir a criação de perfil utilizando o comprimento máximo para o campo de usuário. Para isso, iremos criar uma validação no campo de usuário que não permita o uso de espaço e caso o usuário insira o espaço o aplicativo deverá dar um feedback ao usuário e não permitir que siga com o cadastro.  |
| **Pós-condições**         | A aplicação aguarda nome de usuário seguindo o padrão indicado. |
| **Resultado do teste**  | XXXXXXX  |
| **Resultado Encontrado**    | A aplicação não permite cadastro, utilizando o comprimento máximo para o campo de usuário.    |

**Comment by Rodrigo-Motta-QA** [comment]
Caso de teste 01 Passou
Caso de teste 02 Passou
Caso de teste 03 Passou
Caso de teste 04 Passou
Caso de teste 05 Falhou: Campo não permite a utilização de nomes que contenha sinais diacríticos ( í, á, é, ç,........ )



![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/f2faffd4-1752-45b8-ada2-7cca0d533337)
