### ISSUE TITLE
Usuário não esta recebendo e-mail após realizar o cadastro

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#411]
## Descrição
Temos casos de usuários que estão realizando o cadastro no aplicativo e não estão recebendo o e-mail para ativação da conta.

## Etapas para reproduzir (se aplicável)

1. Abrir o aplicativo
2. Clicar na opção Cadastre-se
3. Preencher as informações da tela de cadastro
4. Preencher as informações na tela de perfil ou pular esta etapa
5. Finalizar o cadastro
6. Verificar se existe um e-mail na caixa de e-mail informada no cadastro

## Comportamento esperado
Usuário deve receber um e-mail para ativação da conta no e-mail que é informado durante o cadastro no aplicativo.

## Comportamento real
Usuários estão relatando que não recebem o e-mail após realizar o cadastro.

## Capturas de tela ou logs

O caso mais recente foi do usuário que realizou o cadastro com o e-mail: matheuszaghetto@gmail.com e diz não ter recebido o e-mail de ativação de conta.

## Ambiente

Sistema operacional: Android
Navegador (se aplicável): N/A
Versão do app: Produção

## Cenários de Teste

- [ ] **Cenário:** 
**Dado** 
**Quando** 
**Então** 

## Informações adicionais

- Verificar se é possível confirmar o envio do e-mail após o cadastro, precisamos entender se existem casos onde o sistema realmente não esta enviado o e-mail ou se o sistema enviou o e-mail e, por algum motivo, não chegou na caixa de e-mail do usuário cadastrado.
- temos logs dos e-mails enviados no fluxo de cadastro ?

**Comment by bruno-luzardi** [comment]
@ValterGabriell conforme falamos, a Mabel informou que o e-mail olhardepagu@gmail.com não recebeu o e-mail para confirmação da conta. Por se tratar de um caso mais recente precisamos utiliza-lo na análise deste problema.

**Comment by ValterGabriell** [comment]
![image](https://github.com/Is-It-Safe/mobile/assets/63808405/d0a01490-5c41-4cd7-a2a5-b0e7b6e839b4)
Ambos os emails informados foram encontrados na base de dados, logo está sendo passado pelo nosso envio de emails. A razão especifica pela qual os emails nao estao chegando ainda é uma duvida, pode ser problema externo ao nosso tambem, no proprio serviço da Google.
