### ISSUE TITLE
Corrigir erro ao adicionar review em um local cadastrado no aplicativo

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#412]
## Descrição
O aplicativo esta apresentado erro quando o usuário buscar por um local, abre o cadastro do local e clica na opção de adicionar review.

## Etapas para reproduzir (se aplicável)

1. Abrir o aplicativo
2. Realizar o login
3. Acessar o menu buscar
4. Pesquisar por um local que esteja cadastrado no aplicativo
5. Abrir o cadastro do local
6. Clicar na opção de adicionar review (opção + no canto inferior direito da tela )
7. Após clicar na opção o aplicativo abre uma tela de erro

## Comportamento esperado
Ao pesquisar por um local, abrir o cadastro do local e clicar na opção de adicionar review o aplicativo deve abrir a tela de adição de review e permitir que o usuário insira uma review.
Ao pesquisar por um local, abrir o cadastro do local e clicar na opção de adicionar review o aplicativo deve abrir a tela de adição de review, caso o usuário desista da operação e feche a tela de review o aplicativo deverá voltar na tela de local pesquisado.

## Capturas de tela ou logs

https://github.com/Is-It-Safe/mobile/assets/136942442/9c801d40-dad4-4bff-868c-3e37073164c0

![Image](https://github.com/Is-It-Safe/mobile/assets/136942442/7c5dbb8c-0d8d-4cc6-92e0-19678a622f87)

## Ambiente

Sistema operacional: Android
Navegador (se aplicável): N/A
Versão do app: Produção (play Store)

## Cenários de Teste

- [x] **Cenário:** Adicionar review após buscar por um local
**Dado** que esteja no menu buscar
**Quando** pesquisar por um local
**E** abrir o cadastro do local
**E** clicar na opção de adicionar review
**Então** o aplicativo deverá abrir a tela de review
**E** permitir que seja inserida uma review ao local

- [x] **Cenário:** cancelando a adição de review a um local
**Dado** que esteja no menu buscar
**Quando** pesquisar por um local
**E** abrir o cadastro do local
**E** clicar na opção de adicionar review
**Então** o aplicativo deverá abrir a tela de review
**Mas** se desistir da operação
**E** fechar a tela de review o aplicativo deverá voltar a tela anterior com o local pesquisado

**Comment by flaviomelodev** [comment]
Redirecionando para a tela de Review

https://github.com/Is-It-Safe/mobile/assets/58519231/1efee7ab-fa24-4288-af47-fdf7e22a2244

**Comment by Rodrigo-Motta-QA** [comment]
| **ID do Caso de Teste** | CT#412-001                                  |
|--------------------------|----------------------------------------|
| **Descrição**               | Corrigir erro ao adicionar review em um local cadastrado no aplicativo |
| **Pré-condições**        | 1. Ter acesso a pagina de criação de perfil no App    |
| **Passos de Execução**   | 1. Abrir o aplicativo         |
|                                         | 2. Realizar o login        |
|                                         | 3. Acessar o menu buscar   |
|                                         | 4. Pesquisar por um local que esteja cadastrado no aplicativo   |
|                                         | 5.  Abrir o cadastro do local   |
|                                         | 6.  Clicar na opção de adicionar review (opção + no canto inferior direito da tela)   |
|                                         | 7.  Após preenchimento da avaliação, clicar em enviar  |
| **Dados de Entrada**      | Nome, Usuário, Pronome(Opcional na criação de perfil), E-mail, senha e confirmação de senha  |
| **Resultado Esperado**    | A avaliação enviada com sucesso e uma mensagem "Review enviada com sucesso" é exibida para usuário    |
| **Critérios de Aceitação**| 1. O sistema não apresenta problemas no processo de adicionar review para um local cadastrado. |
| **Pós-condições**         | Usuário continua no local cadastrado após a review |
| **Resultado do teste**  | Passou|


https://github.com/Is-It-Safe/mobile/assets/125081870/3c95876b-063c-4b25-9888-4e0b72a3fbf6
