### ISSUE TITLE
Ajustar rolagem de tela do menu buscar

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#414]
## Descrição
O aplicativo esta apresentado problema na aba de busca quando é realizada uma busca por um termo que retorna vários locais.
Se a quantidade de locais retornados na busca não couber na tela do dispositivo, não esta sendo possível rolar a tela para visualizar todos os registros que são listados como resultado da busca.

## Etapas para reproduzir (se aplicável)

1. Abrir o aplicativo
2. Realizar o login
3. Acessar o menu buscar
4. Pesquisar por locais utilizando um termo que retorne vários locais
5. Rolar a tela para visualizar todos os registros que foram retornados na busca

## Comportamento esperado
Permitir a rolagem da tela para que seja possível visualizar todos os registros listados como resultado de uma busca.

## Capturas de tela ou logs

https://github.com/Is-It-Safe/mobile/assets/136942442/82d3a410-0a06-4203-a37b-9933c7592fe3

## Ambiente

Sistema operacional: Android
Navegador (se aplicável): N/A
Versão do app: Produção (play Store)

## Cenários de Teste

- [ ] **Cenário:** Visualizar todos os locais listados no resultado de uma busca
**Dado** que esteja no menu buscar
**Quando** pesquisar por um termo
**E** a busca retorna vários locais
**Então** o aplicativo deverá permitir a rolagem da tela para visualizar todos os locais retornados na busca

**Comment by Rodrigo-Motta-QA** [comment]
| **ID do Caso de Teste** | CT#414-001                                  |
|--------------------------|----------------------------------------|
| **Descrição**               | Ajustar rolagem de tela do menu buscar  |
| **Pré-condições**        | 1. Ter uma conta válida cadastrada na aplicação.  |
| **Passos de Execução**   | 1. Fornecer e-mail válido           |
|                                         | 2. Fornecer senha valida         |
|                                         | 3. Clicar em login  |
|                                         | 4. Realizar uma busca por locais já cadastrados   |
|                                         | 5.  Utilizar gestos de skroll up e skroll down na lista de locais apresentada como resultado da busca.   |
| **Dados de Entrada**      | E-mail válido e senha válida  |
| **Resultado Esperado**    | A aplicação deve permitir executar os gestos se skroll up e skroll down na lista de locais apresentada.     |
| **Critérios de Aceitação**| 1. Permitir a rolagem da tela para que seja possível visualizar todos os registros listados como resultado de uma busca. |
| **Pós-condições**         | N/A |
| **Resultado do teste**  | Passou |


https://github.com/Is-It-Safe/mobile/assets/125081870/10099bae-8e02-43df-b789-63bb85e38467
