### ISSUE TITLE
Incluir a versão do aplicativo na tela de login

### ISSUE THREAD

**Issue by bruno-luzardi** [Is-It-Safe/mobile#440]
## User Story

**COMO** usuário do app
**QUERO** visualizar a informação sobre a versão do aplicativo
**PARA** saber se estarei utilizando a versão mais recente no meu dispositivo

## Descrição
Incluir a informação sobre a versão do app no rodapé da tela de login para que seja possível saber qual versão do app o usuário possui instalado e em uso.

## Critério de Aceite

- [x] A informação de versão deverá ser exibida no rodapé da tela, com o texto alinhado a esquerda.
- [x] A informação de versão deverá ser exibida somente na tela de login.
- [x] Seguir o design do Figma

https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?type=design&node-id=7119-9129&mode=design&t=VBvGLflIklWXMXzX-4

### Testar inclusão da versão do aplicativo na tela de login 
**Dado** que o aplicativo está instalado e funcionando corretamente
**Quando** eu verifico se há um campo/classe dedicado para exibir a versão na tela de login
**Então** o campo/classe para exibir a versão está presente

## Objetivo:
Verificar se a versão do aplicativo é exibida corretamente na tela de login, garantindo transparência sobre a versão atual para usuários e facilitando o suporte técnico.

### Verificação da Exibição da Versão
- [ ] Verificar se há um campo/classe dedicado para exibir a versão do aplicativo na tela de login.

### Identificação da Versão Atual
- [ ] Identificar a versão atual do aplicativo (pode ser obtida a partir de um arquivo de manifesto ou similar).

### Exibição Correta da Versão
- [ ] Confirmar se a versão identificada está sendo exibida corretamente na tela de login.
- [ ] Verificar se a formatação está apropriada e se não há cortes ou sobreposições de texto.

### Teste de Atualização Automática
- [ ] Realizar uma atualização do aplicativo para uma versão mais recente.
- [ ] Verificar se a versão exibida na tela de login é automaticamente atualizada.

### Validação de Tela Responsiva
- [ ] Testar a exibição da versão em diferentes dispositivos (se aplicável).
- [ ] Verificar se a versão é apresentada de maneira responsiva em telas de diferentes tamanhos e orientações.

## Pós-Condições
- [ ] A versão do aplicativo deve ser exibida corretamente na tela de login.
- [ ] A atualização automática da versão deve ser refletida imediatamente após uma atualização do aplicativo.
- [ ] Não deve haver erros críticos ou falhas durante os testes.

## Informações Adicionais

Neste momento iremos apenas incluir a inf. de versão na tela de login, pois na reestruturação do app iremos criar uma tela para esta informação.

**Comment by Rodrigo-Motta-QA** [comment]
Caso de teste 01: Passou


![Image](https://github.com/Is-It-Safe/mobile/assets/125081870/6f287809-83a3-47fc-bbfc-840a35657923)
